jtroo/kanata

src/oskbd/linux.rs

Fix cross-platform issue and incorrect uinput name

---

src/oskbd/linux.rs

Limit keybit to 256 to fix wayland issue, add syscall rc checks

---

Cargo.lock
Cargo.toml
README.md
cfg_samples/kanata.kbd
src/cfg.rs

Add tap-dance and one-shot actions

---

justfile
src/cfg.rs
src/custom_action.rs
src/kanata.rs
src/main.rs

Fix multi action for specific functionality

---

Cargo.lock
Cargo.toml
cfg_samples/kanata.kbd
src/cfg.rs

Add release-key and release-layer

---

Cargo.lock
Cargo.toml
src/kanata.rs
src/main.rs
src/tcp_server.rs

Execute layer changes via tcp socket messages

---

src/keys/windows.rs

Same as pull request #63 but for Windows (at work I have a Windows to test on). Issues #64, #21

Fix key ro for Windows

---

src/cfg.rs
src/main.rs

fix: move a log message to be more sensible

---

README.md
cfg_samples/kanata.kbd

doc: improve key alias discoverability

---

README.md

doc: add repology badge

---

Cargo.lock
Cargo.toml
src/cfg.rs
src/custom_action.rs
src/kanata/linux.rs
src/kanata/mod.rs
src/keys/linux.rs
src/layers.rs
src/main.rs
src/oskbd/linux.rs

Refactor multi action, switch evdev-rs to evdev again to fix mouse buttons

---

cfg_samples/kanata.kbd
src/cfg.rs
src/custom_action.rs
src/kanata/mod.rs
src/oskbd/linux.rs
src/oskbd/windows.rs

Closes #33.
Doesn't include extra mouse buttons (e.g. fwd, back), but a separate issue can be opened for those if desired.

Add vertical and horizontal mouse scroll actions

---

Cargo.lock
Cargo.toml
src/oskbd/linux.rs

Closes #61 
@jian-lin does this work correctly?

fix(symlink): upgrade to evdev 0.11.6 and fix symlink

---

Cargo.lock
Cargo.toml
cfg_samples/jtroo.kbd
cfg_samples/kanata.kbd
src/cfg.rs
src/custom_action.rs
src/kanata/mod.rs
test_cfgs/ancestor_seq.kbd
test_cfgs/descendant_seq.kbd

Implement leader->sequence->fakekey tap

---

src/oskbd/windows.rs

Fixes a soundness issue I found in the original [kbremap](https://github.com/timokroeger/kbremap/blob/main/src/keyboard_hook.rs) code.
Drop code is not guaranteed to run (e.g. when using `mem::forget`).
Thus we cannot rely on drop unregistering the hook.
Make the hook abstraction require a static lifetime for the closure to ensure crash free operation in any case.
Program to reproduce the issue:
``` Rust
fn main() {
{
let mut pressed_keys = Vec::with_capacity(1);
let hook = KeyboardHook::set_input_cb(|ev| {
pressed_keys.push(ev);
false
});
mem::forget(hook);
}
unsafe {
let mut msg = mem::zeroed();
GetMessageW(&mut msg, ptr::null_mut(), 0, 0);
}
}
```

Static lifetime for the low-level keyboard hook

---

Cargo.lock
Cargo.toml
src/kanata/mod.rs

perf: allow processing loop to block when ok

---

cfg_samples/kanata.kbd
src/oskbd/linux.rs

fix: allow colons in device path using a backslash

---

cfg_samples/kanata.kbd
src/cfg.rs

feat: add altgr chord shortcut to enable it in macros

---

src/kanata/mod.rs
src/oskbd/linux.rs

It uses a simple heuristic, checking if the device supports the enter key.

autodetect keyboard devices if they are not provided on linux

---

src/cfg.rs
src/kanata/mod.rs

fix: allow key repeat for tap-dance and one-shot

---

cfg_samples/kanata.kbd
src/cfg/mod.rs
src/custom_action.rs
src/kanata/mod.rs

feat: add repeat key

---

src/kanata/linux.rs
src/kanata/mod.rs
src/kanata/windows/interception.rs
src/kanata/windows/llhook.rs

feat: lctl+spc+esc now terminates kanata

---

src/oskbd/linux.rs

Thanks for merging the previous PR, I just wanted to add a little bit to it, but you were to fast :).
This PR completes all relative axes (exotic, but at least feature exhaustive).
Also theoretically not all keys are supported (previously `300` vs `0x300` which is the max defined in `libc::KEY_CNT`).
For some arcane reason the range `0..0x300` didn't work, the virtual device created with it did nothing at all, but subranges like `0x250..0x300` did work. The biggest range that I've got to work is `0..560`. Well this should at least support *more* possible keys...
Mouses are now recognized separately in the `is_input_device` filter.
I also added this comment:
```rust
// TODO investigate the rare possibility that a device is e.g. a Joystick and a Keyboard or a Mouse at the same time, which …
```

Small refactoring and fixes in the virtual device creation of `KbdOut` in Linux

---

cfg_samples/minimal.kbd
src/kanata/linux.rs
src/kanata/windows/interception.rs
src/kanata/windows/llhook.rs

fix: make unmapped keys trigger tap-hold-(press|release)

---

Cargo.toml

fix: update kanata-keyberon for one-shot fixes

---

cfg_samples/kanata.kbd
docs/config.adoc
src/cfg/mod.rs

feat: allow chorded sub-macro in a macro

---

src/keys/mod.rs

fix: map kp0 correctly

---

src/main.rs
src/oskbd/linux.rs

feat: be more lenient for missing linux device

---

src/keys/mod.rs
src/keys/windows.rs

feat: add mappings for japanese keys

---

src/oskbd/linux.rs

fix(linux): deregister and reregister devices

---

src/kanata/mod.rs

fix: add sequence state check to can_block

---

cfg_samples/kanata.kbd
docs/config.adoc
src/cfg/mod.rs
src/custom_action.rs
src/kanata/mod.rs

feat: add dynamic macro

---

docs/config.adoc
src/kanata/mod.rs
src/keys/mod.rs
src/main.rs
src/oskbd/linux.rs

feat(linux): allow unicode behaviour customization

---

cfg_samples/kanata.kbd
docs/config.adoc
src/cfg/mod.rs
src/custom_action.rs
src/kanata/mod.rs
src/keys/windows.rs
src/oskbd/linux.rs
src/oskbd/windows/interception.rs
src/oskbd/windows/llhook.rs

feat: send arbitrary key numbers

---

docs/config.adoc
src/cfg/key_override.rs
src/cfg/mod.rs
src/kanata/mod.rs

feat: add global key override `defoverrides`

---

cfg_samples/kanata.kbd
docs/config.adoc
src/cfg/mod.rs
src/custom_action.rs
src/kanata/mod.rs
src/main.rs

feat: lrld-next + lrld-prev

---

src/kanata/mod.rs

fix(dynamic-macro): ensure all keys are released

---

docs/config.adoc
src/cfg/mod.rs
src/custom_action.rs
src/kanata/cmd.rs
src/kanata/mod.rs

feat: add cmd variant that outputs keys

---

src/cfg/mod.rs

Should probably leave this PR out for a while for visibility that some configurations may break.

feat: error on invalid top-level config items

---

README.md
docs/release-template.md

doc: document that kanata does not run in the background

---

cfg_samples/kanata.kbd
docs/config.adoc
src/cfg/mod.rs
src/cfg/sexpr.rs
src/cfg/tests.rs

feat: add `defvar` to allow defining variables

---

Cargo.lock
Cargo.toml
cfg_samples/kanata.kbd
docs/config.adoc
keyberon/src/action.rs
keyberon/src/layout.rs
src/cfg/mod.rs

feat(oneshot): add variants for release and cancel on repress

---

Cargo.lock
Cargo.toml
cfg_samples/kanata.kbd
docs/config.adoc
keyberon/src/action.rs
keyberon/src/layout.rs
src/cfg/mod.rs
src/cfg/tests.rs

feat: add `fork` action

---

cfg_samples/kanata.kbd
docs/config.adoc
src/cfg/mod.rs
src/cfg/tests.rs
src/custom_action.rs
src/kanata/caps_word.rs
src/kanata/mod.rs

feat: add caps-word

---

src/cfg/mod.rs

This commit fixes poor errors and a delay bug with the macro actions:
- error messages for out-of-range numbers are treated correctly
- error messages for invalid values point to the correct value
- putting a delay at the end of the macro now works
Of note in the last bug is the keyberon code does not handle a delay at the end correctly. This is worked around by adding a `Complete` event at the end of all macros.

fix(macro): improve errors, fix delay at end

---

src/kanata/mod.rs

fix(rpt): follow caps-word

---

cfg_samples/kanata.kbd
docs/config.adoc
src/cfg/mod.rs
src/cfg/tests.rs

feat: defaliasenvcond

---

src/keys/mappings.rs

fix: add missing keys to mappings

---

src/cfg/mod.rs
src/cfg/tests.rs
test_cfgs/unknown_defcfg_opt.kbd

feat!: error on unknown defcfg option

---

Cargo.lock
Cargo.toml
docs/config.adoc
keyberon/Cargo.toml
keyberon/src/action.rs
src/cfg/mod.rs
src/cfg/tests.rs
src/kanata/mod.rs
src/keys/linux.rs
src/keys/windows.rs
src/main.rs
src/sequences.rs

feat: support chords in defseq keys

---

src/kanata/mod.rs

fix(chord): remove repeat chord keypress

---

cfg_samples/kanata.kbd
docs/config.adoc
src/cfg/mod.rs
src/kanata/linux.rs
src/kanata/mod.rs
src/kanata/windows/mod.rs
src/oskbd/linux.rs

Implements #432 
Seems to work as expected in my brief testing.

feat: add config to set X11 repeat rate

---

cfg_samples/kanata.kbd
docs/config.adoc
src/cfg/mod.rs
src/cfg/tests.rs

feat: add cfg to delegate transparent keys to first layer

---

src/keys/windows.rs

fix: swiss keyboard $ on Windows

---

keyberon/src/layout.rs

In the keyberon `do_action` function, most action types trigger a check to end a one-shot action if applicable. Notable exclusions are actions that will always trigger other actions.
The excluded cases are:
- Repeat
- HoldTap
- TapDance
- Chords
- MultipleActions
- Fork
Closes #462

fix: trigger one-shot to end with other actions

---

Cargo.toml

https://github.com/jtroo/kanata/issues/452#issuecomment-1611858389

fix: cargo features in subcrate

---

parser/src/cfg/mod.rs

fix!: disallow invalid boolean defcfg values

---

Cargo.lock
parser/Cargo.toml
parser/src/cfg/mod.rs
parser/src/keys/linux.rs
parser/src/keys/mod.rs
src/kanata/mod.rs
src/kanata/windows/interception.rs
src/oskbd/linux.rs
src/oskbd/mod.rs
src/oskbd/windows/interception.rs
src/oskbd/windows/llhook.rs
src/oskbd/windows/mod.rs

Closes https://github.com/jtroo/kanata/discussions/482#discussioncomment-6392925

refactor: make parser compilable to wasm

---

keyberon/src/layout.rs

fix: handle waiting states in action queue

---

docs/config.adoc

doc: fix switch action header

---

docs/config.adoc
parser/src/keys/mod.rs

fix!: map unicode yen to KEY_YEN

---

cfg_samples/kanata.kbd
docs/config.adoc

doc(linux,tap-hold): document linux tap-hold repeat issue

---

cfg_samples/kanata.kbd
docs/config.adoc
parser/src/cfg/mod.rs
src/kanata/mod.rs
src/oskbd/linux.rs
src/oskbd/windows/interception.rs
src/oskbd/windows/llhook.rs

Make #568 work on Windows. Testing if still works on Linux via pipeline.

feat: add movemouse-smooth-diagonals

---

docs/locales.adoc

- Add documentation to docs/locales.adoc

docs: add french source layout

---

src/kanata/mod.rs

fix!(seq): release keys in valid visible-backspaced sequence

---

cfg_samples/kanata.kbd
docs/config.adoc
parser/src/cfg/list_actions.rs
parser/src/cfg/mod.rs
parser/src/custom_action.rs
src/kanata/mod.rs

feat: add unmod action

---

docs/config.adoc

Fix off-by-one error in config.adoc

---

src/oskbd/windows/interception.rs

fix(wintercept): send Esc for unmapped oscode

---

README.md

doc: add "community projects" section to README

---

src/main.rs
src/oskbd/linux.rs

feat(linux): add configurable delay for registering devices

---

.github/workflows/macos-build.yml
Cargo.lock
Cargo.toml

bump driverkit to v0.1.1

---

cfg_samples/kanata.kbd
docs/config.adoc
keyberon/src/layout.rs
parser/src/cfg/defcfg.rs
parser/src/cfg/mod.rs
parser/src/cfg/tests.rs

feat(defcfg): add multi-tap-hold-quick-timeout

---

docs/kmonad_comparison.md

Update comparison to kmonad to make clear that MacOS is supported.

Mac OS support is not an advantage of kmonad anymore

---

Cargo.lock
Cargo.toml

chore: bump driverkit to 0.1.3

---

cfg_samples/kanata.kbd
parser/src/cfg/mod.rs

Closes https://github.com/jtroo/kanata/issues/720

doc: comment include in kanata.kbd sample

---

Cargo.lock
cfg_samples/kanata.kbd
docs/config.adoc
parser/Cargo.toml
parser/src/cfg/deftemplate.rs
parser/src/cfg/mod.rs

Add a feature to aid with repetitive configurations.

feat: add `deftemplate` and `template-expand`

---

cfg_samples/kanata.kbd
docs/config.adoc
parser/src/cfg/deftemplate.rs
parser/src/cfg/tests.rs

feat: add `if-equal` within deftemplate

---

example_tcp_client/src/main.rs
parser/Cargo.toml
parser/src/cfg/mod.rs
src/kanata/mod.rs
src/main.rs
src/oskbd/mod.rs
src/oskbd/windows/interception.rs
src/oskbd/windows/mod.rs
src/tcp_server.rs

feat(tcp): add fake key action and structured errors

---

Cargo.lock
cfg_samples/kanata.kbd
docs/config.adoc
keyberon/Cargo.toml
keyberon/src/action/switch.rs
keyberon/src/layout.rs
parser/src/cfg/mod.rs
parser/src/cfg/switch.rs
parser/src/cfg/tests.rs
src/kanata/mod.rs

feat(switch): add key-timing

---

docs/locales.adoc

- add turkish locale
- change a http link in french layout to https
- change wording in the french layout a bit for consistency

Add Turkish locale

---

src/tcp_server.rs
tcp_protocol/src/lib.rs

add `RequestCurrentLayerInfo`
potentially may partially resolve #811
- tested manually

feat(tcp): add RequestCurrentLayerInfo (#811)

---

parser/src/cfg/list_actions.rs
parser/src/cfg/mod.rs
parser/src/custom_action.rs
src/kanata/mod.rs

add `lrld-file` action 
may resolve #806 

feat: add `lrld-file` action (#806)

---

keyberon/src/action/switch.rs
parser/src/cfg/switch.rs
parser/src/cfg/tests.rs

Should implement https://github.com/jtroo/kanata/issues/782

feat(switch,parser): add parsing for input

---

src/filesim.rs

fix a typo

---

parser/src/keys/mod.rs

feat(keycodes): add keypad comma

---

parser/src/keys/mod.rs
src/oskbd/windows/llhook.rs

fix(win-llhook): differentiate kprt

---

.github/workflows/rust.yml
Cargo.toml
src/filesim.rs
src/kanata/cmd.rs
src/kanata/linux.rs
src/kanata/mod.rs
src/lib.rs
src/main.rs
src/oskbd/linux.rs
src/oskbd/macos.rs
src/oskbd/mod.rs
src/oskbd/simulated.rs
src/oskbd/windows/interception.rs
src/oskbd/windows/llhook.rs
src/oskbd/windows/mod.rs

POC for #816

---

keyberon/src/action/switch.rs
parser/src/cfg/fake_key.rs
parser/src/cfg/list_actions.rs
parser/src/cfg/mod.rs
parser/src/cfg/switch.rs
parser/src/cfg/tests.rs
src/kanata/mod.rs
src/tcp_server.rs

Improve "fake key" naming and actions: #790

feat(fakekeys): change naming to virtual, add new actions

---

cfg_samples/kanata.kbd
docs/config.adoc
parser/src/cfg/mod.rs

add a way to map any key in `deflayer-custom-map`, with 1 line/triplet 
may resolve #877 

add a way to map any key in `deflayer-custom-map`

---

parser/src/cfg/mod.rs
parser/src/cfg/os_dependent.rs
parser/src/cfg/tests.rs

feat: platform specific top-level item

---

docs/config.adoc

doc: fix broken link in config.adoc

---

justfile
keyberon/src/chord.rs
parser/src/cfg/is_a_button.rs
src/kanata/mod.rs

Fix timing/idling issues in experimental chords and remove test prints.

fix(chordsv2): remove test logging, handle idling correctly

---

docs/locales.adoc

Not much to say, just adding the azerty macos layout I made as a ressource for people to use.
(Based on the existing qwertz macos layout already available)

Updating locales.adoc with AZERTY layout for Macos

---

docs/setup-linux.md

Add an example OpenRC init script for kanata along with the appropriate commands.

add an OpenRC init script for running kanata at startup with user privileges

---

docs/release-template.md
justfile

Adds automatic builds for the windows library that can be used with AutoHotkey
- n/a
- n/a
- n/a
- n/a

Add kanata_passthru.dll to release just workflow

---

cfg_samples/kanata.kbd
docs/config.adoc
parser/src/cfg/list_actions.rs
parser/src/cfg/mod.rs
parser/src/custom_action.rs
src/kanata/mod.rs
src/tests/sim_tests/capsword_sim_tests.rs
src/tests/sim_tests/mod.rs

feat: `caps-word-toggle`

---

docs/config.adoc
src/kanata/cmd.rs
src/kanata/mod.rs

feat(cmd): parse numeric delay

---

docs/config.adoc
simulated_passthru/ReadMe.md

doc: fix links

---

src/kanata/mod.rs
src/tests/sim_tests/mod.rs
src/tests/sim_tests/override_tests.rs

fix: move overrides code to after unmod

---

Cargo.toml

also split gui deps by groups to make it easier to edit/merge later
- N/A
- N/A
- N/A

dep(gui): remove unused deps

---

src/oskbd/macos.rs

fix: Mouse clicks need CGMouseButton

---

parser/src/cfg/defcfg.rs
src/kanata/mod.rs
src/kanata/windows/interception.rs

feat(win-interception): add device exclusion to defcfg

---

src/oskbd/windows/interception_convert.rs
src/oskbd/windows/scancode_to_usvk.rs

Try adding code for previously-unmapped JIS keys. Not tested. #1160.

feat(win): map (no)convert scancodes

---

docs/setup-linux.md

this pr aims to resolve issues #1153 and #1179 by providing more details in the setup guide on how to expand the PATH env in the systemd service file

new note in systemd service guide

---

parser/src/cfg/mod.rs

log: add warning for compose usage

---

cfg_samples/kanata.kbd
docs/config.adoc
keyberon/src/action/switch.rs
keyberon/src/layout.rs
parser/src/cfg/switch.rs
src/tests/sim_tests/switch_sim_tests.rs

feat(switch): add `base-layer`

---

cfg_samples/colemak.kbd
cfg_samples/kanata.kbd
docs/config.adoc
parser/src/cfg/chord.rs
parser/src/cfg/defcfg.rs
parser/src/cfg/mod.rs
src/tests/sim_tests/chord_sim_tests.rs

Allow omitting -experimental and add warning for using -experimental.

feat(chordsv2): allow omitting -experimental

---

README.md

Adds another similar project that is configurable in .yaml format. Works on Linux (Xorg/Wayland).
- [N/A] Yes or N/A
- [N/A] Yes or N/A
- [N/A] Yes or N/A
- [N/A] Yes

Added mouseless in README

---

Cargo.lock
Cargo.toml

Bump driverkit to v.0.1.4

---

README.md

Update link to VirtualHidDevice Driver

---

cfg_samples/kanata.kbd
docs/config.adoc
parser/src/cfg/list_actions.rs
parser/src/cfg/mod.rs
parser/src/custom_action.rs
src/kanata/mod.rs
src/tests/sim_tests/macro_sim_tests.rs
src/tests/sim_tests/mod.rs

feat: macro-cancel-on-press

---

cfg_samples/kanata.kbd
keyberon/src/action.rs
keyberon/src/layout.rs
parser/src/cfg/key_outputs.rs
parser/src/cfg/list_actions.rs
parser/src/cfg/mod.rs
src/tests/sim_tests/mod.rs
src/tests/sim_tests/oneshot_tests.rs

feat(oneshot): add one-shot-pause-processing

---

src/kanata/output_logic/zippychord.rs
src/tests/sim_tests/zippychord_sim_tests.rs

feat(zippy): optimize w.r.t. common prefix

---

cfg_samples/kanata.kbd
docs/config.adoc
parser/src/cfg/zippychord.rs
src/kanata/output_logic/zippychord.rs
src/tests/sim_tests/zippychord_sim_tests.rs

Zippy noerase

---

docs/release-template.md

Found small error while looking up how to install, I figured a PR would be quicker than opening an issue.

Fix mistake in release template

---

docs/config.adoc

Added clarification that fork is the equivalent of the basic key checks in switch, using none of the list logic items.
Per [Discussion #1422](https://github.com/jtroo/kanata/discussions/1422)
- N/A
- N/A

Update config.adoc fork section

---

README.md

Add nata application-aware switching layer

---

README.md

Update README to reflect that the macOS community project has been renamed due to the addition of input source observation

doc: rename macOS community project from README

---

docs/simulated_passthru_ahk/kanata_passthru.ahk

Minor updates while investigating a bug
move dll's log level to the initial "config" area for higher visibility
fix typo
shorten debug log

doc(passthru): update AutoHotkey passthru example

---

src/kanata/mod.rs
src/oskbd/windows/interception.rs
src/oskbd/windows/llhook.rs
src/oskbd/windows/mod.rs

fix(windows): arbitrary code sends raw number

---

Cargo.lock
Cargo.toml
cfg_samples/kanata.kbd
docs/config.adoc
parser/src/cfg/list_actions.rs
parser/src/cfg/mod.rs
parser/src/cfg/tests.rs
parser/src/custom_action.rs
src/kanata/clipboard.rs
src/kanata/mod.rs

feat: add clipboard functionality

---

README.md

Add **hyprkan** to Application-aware layer switching list

Add hyprkan

---

cfg_samples/kanata.kbd
docs/config.adoc
keyberon/src/action.rs
keyberon/src/layout.rs
parser/src/cfg/mod.rs
src/tests/sim_tests/tap_hold_tests.rs

feat: add `reset-timeout-on-press` to `tap-hold-release-timeout`

---

.github/workflows/rust.yml
cfg_samples/kanata.kbd
docs/config.adoc
justfile
parser/src/cfg/fake_key.rs
parser/src/cfg/list_actions.rs
parser/src/cfg/mod.rs
parser/src/custom_action.rs
src/kanata/caps_word.rs
src/kanata/linux.rs
src/kanata/macos.rs
src/kanata/mod.rs
src/kanata/unknown.rs
src/kanata/windows/mod.rs
src/tests/sim_tests/delay_tests.rs
src/tests/sim_tests/mod.rs
src/tests/sim_tests/vkey_sim_tests.rs

feat: `on-physical-idle` for vkeys

---

src/main.rs

I can add a test and update docs if you'd like.  my focus was getting fmt right!

feat(cli): read config via --cfg-stdin

---

keyberon/src/layout.rs
src/tests/sim_tests/mod.rs
src/tests/sim_tests/tap_hold_tests.rs
src/tests/sim_tests/vkey_sim_tests.rs

fix: avoid reset of tap repress timeout for vkeys
