jtroo/kanata

- Cargo.lock
- Cargo.toml
- src/cfg.rs
- src/kanata.rs
The motivation behind this change is for getting accustomed to new
layout changes. The log may be of benefit so that the user can see what
layout they're currently on and what keys are associated with it.
The info-level logs are currently empty apart from initialization, so
may as well make it useful for something.
One current limitation is that any comments in the original layout file
won't exist in the printed text.
Additional changes:
- increment version
- refactor handle_time_ticks into multiple fns
- change to new kanata-keyberon version for pub fn current_layer
> Print layer as info log when layer changes

- src/cfg.rs
- test_cfgs/nested_tap_hold.kbd
This fixes the issue of unexpected behaviour from nested tap-hold by
disabling nested tap-hold. This prevents a user from spending
unnecessary time testing out the configuration and realizing it doesn't
work in the expected way.
> Disable nested tap-hold

- Cargo.lock
- Cargo.toml
- src/keys/linux.rs
- src/oskbd/linux.rs
Please refer to commit messages for more information.
I make this pr to prepare for adding a functionality of creating a symlink for the newly created virtual device, e.g. `/dev/input/by-id/kanata0 -> /dev/input/event30`, which is useful if you want to pass the created virtual device into qemu.
> Bump evdev-rs and remove uinput-sys

- Cargo.lock
- Cargo.toml
- src/keys/linux.rs
- src/oskbd/linux.rs
This reverts commits:
- bcbb5ec895e274b22ae060a1299e585560af2f95.
- 2e66b323efaadf352ca7471165490d65028247e4.
The reason for doing this is that evdev-rs=0.5.0, evdev-sys=0.2.4 have
a bug where they aren't cached properly and get recompiled on every
build/test/check. This is degrades the development workflow on Linux.
The issue has been fixed but there is no version published to crates.io
that includes the fix.
See: https://github.com/ndesh26/evdev-rs/issues/88
> Revert changes to evdev-rs and uinput crates

- Cargo.lock
- Cargo.toml
- src/kanata.rs
- src/keys/linux.rs
- src/oskbd/linux.rs
The evdev crate is added and these dependencies are dropped:
- libc
- uinput-sys
- evdev-rs
Replace uinput-sys with evdev because evdev is a wrapper library for
evdev devices that provides interfaces to create uinput devices and send
events. Using evdev is less error-prone than accessing uinput directly,
and should be considered for new software[1]. evdev is also needed to
create a symlink in /dev/input/by-id/
libc is dropped since its struct definitions are no longer required.
evdev-rs is replaced by evdev so that the system library libevdev is no
longer a dependency.
[1]: https://www.kernel.org/doc/html/latest/input/uinput.html
> Use evdev to create and write device

- src/keys/linux.rs
- src/keys/mod.rs
Key ro is the slash key for some keyboard layout such as ABNT2 #21
> Add key ro alias for Linux

- cfg_samples/kanata.kbd
- src/kanata.rs
- src/keys/windows.rs
- src/main.rs
- src/oskbd/windows.rs
Attempted mitigation for #55.
Since I don't use an international layout, I'm not sure how effective this is in fixing the actual issue. However, it works as designed with regards to the input/output of key events.
> Mitigate Windows altgr issue

- src/keys/mod.rs
I suggest having an additional alias for Print Screen.
We keep `sys` for SysReq on Linux and `prnt` for Print Screen on Windows to keep compatible with KMonad. But add a `prtsc` alias which is SysReq on Linux or Print Screen on Windows. So I can have one single config which works for both. Since the physical key is the same on ordinary keyboards.
What do you think about that idea?
> Add prtsc conditional alias (sys for Linux or prnt Windows)

- src/keys/mod.rs
Adds an alias for the mute key to be used in layer definitions.
> feat(keycodes): add mute

- cfg_samples/kanata.kbd
- src/cfg.rs
Add support for keyberon's HoldOnOtherKeyPress and PermissiveHold options for tap-hold.
Hope my docs are clear. I couldn't think of an example that wasn't redundant there. They all do the same thing, only on slightly different moments.
> Add support for keyberon's HoldOnOtherKeyPress and PermissiveHold

- cfg_samples/kanata.kbd
- src/cfg.rs
- src/custom_action.rs
- src/kanata/mod.rs
- src/layers.rs
- src/oskbd/linux.rs
This commit adds full functionality of the fake keys feature. Examples
and descriptions of intended use cases are added to the kanata.kbd file.
Closes #80
> feat(fake-keys): add fake keys feature

- cfg_samples/kanata.kbd
- src/cfg.rs
This commit adds an alternate action name for layer-toggle:
layer-while-held
This is added because the word "toggle" does not quite precisely
describe what the action actually does.
A miscellaneous change included in this commit is adding some missing
action names in an error message and changing the error message's format
to group related commands together.
Closes #81
> feat: add alias for layer-toggle: layer-while-held

- example_tcp_client/src/main.rs
- src/cfg.rs
- src/kanata/mod.rs
- src/main.rs
- src/oskbd/linux.rs
- src/oskbd/windows.rs
- src/tcp_server.rs
All expect messages are adjusted or replaced with unwrap following the
guidelines here:
https://github.com/rust-lang/project-error-handling/issues/50
https://github.com/rust-lang/rust/pull/96033
> refactor: adjust expect messages

- src/cfg.rs
- src/cfg/sexpr.rs
- src/kanata/mod.rs
The parser has been reworked to be much more readable and short, staying away from "shotgun style" parsing. This also fixes multiple correctness issues. These are some examples of strings that should parse, but don't. They also fail with confusing error messages.
```
(asdf())
```
```
(asdf adsf
(asdf(asdf)))
```
```
(asdf ()) (asdf ())
```
The new parser also performs much faster, parsing everything in one pass without recursion.
I removed the `layer_info` field as it seems to be used for debugging only. If the layer ast has to be printed, we can print the debug representation or pretty print.
> Rework parser, fix multiple correctness issues, improve speed and readability

- Cargo.lock
- Cargo.toml
the type for `evdev::enumerate` changed
> fix build failure by upgrading evdev to 0.12.0

- cfg_samples/kanata.kbd
- cfg_samples/minimal.kbd
- src/cfg/mod.rs
- src/kanata/linux.rs
- src/kanata/windows/interception.rs
- src/kanata/windows/llhook.rs
This commit adds a new defcfg item and reverts the first attempted fix
for tap-hold-(press|release) not being triggered by keys that are not in
defsrc. The first fix was not correct because the order of keys was
incorrect.
Processing keys missing from defsrc is disabled by default. The reason
this is not enabled by default is because some keys may not work
correctly if they are intercepted. E.g. ralt/altgr on Windows using the
LLHOOK mechanism.
> fix: add defcfg item to process unmapped keys

- cfg_samples/kanata.kbd
- src/kanata/linux.rs
- src/kanata/mod.rs
- src/kanata/windows/mod.rs
Windows has some weirdness with arrow keys and the numpad where one is a shifted version of the other. I think it's a historical issue since physical arrow keys don't have this problem but injected ones do. Might be a bug in SendInput or the LLHOOK mechanism. This is relevant because it's likely related to the point below.
When injecting an arrow key while an injected lsft is held, Windows sends a fake physical lsft release and then a fake physical lsft press event. The kanata-injected arrow event is likely in between the two fake physical events. I think Windows does this because at the OS level, it thinks lsft needs to be released to be able to send an arrow key instead of a numpad key. So since the injected lsft is active in the Windows OS, Windows sends the fake lsft events without …
> fix(windows): release all shift keys on non-physical shift release

- src/cfg/mod.rs
- src/cfg/sexpr.rs
Closes #156 
Not actually tested in practice yet, but a unit test is added which fails before the code change to flatten multi, and passes afterwards.
> fix: flatten multi to fix nested multi with custom

- cfg_samples/kanata.kbd
- docs/config.adoc
- src/cfg/mod.rs
- src/custom_action.rs
- src/kanata/mod.rs
The use case motivating this feature is to be able to hold a key for different amounts of time and outputting different characters with visual feedback on what's getting outputted. It is similar to tap-dance but instead of tapping a key for varying number of repeats, the key is held for a varying amount of time to get the different outputs.
> feat: add cancellable macro

- Cargo.lock
- Cargo.toml
- cfg_samples/kanata.kbd
- docs/config.adoc
- keyberon/Cargo.toml
- keyberon/src/action.rs
- keyberon/src/layout.rs
- src/cfg/mod.rs
This commit enhances the `macro` and `macro-release-cancel` actions by allowing some other special actions to be used inside. Some actions, e.g. `tap-hold` don't make much sense to put in a macro, so are not supported.
The precise list of actions allowed within `macro` are those that correspond to an action in the `CustomAction` enum.
At the time of writing, the list of useful actions supported in macros are:
- cmd
- unicode
- mouse actions
There are more actions that are technically allowed, but seem like they don't make much sense to put inside of a macro. Thus they are not documented:
- fake key actions
- sequence leader
- live reload
- repeat
> feat: allow some special actions in macro

- Cargo.lock
- Cargo.toml
- keyberon/Cargo.toml
- keyberon/src/action.rs
- keyberon/src/hid.rs
- keyberon/src/layout.rs
- src/cfg/mod.rs
- src/kanata/mod.rs
- src/kanata/windows/interception.rs
- src/kanata/windows/llhook.rs
- src/oskbd/linux.rs
- src/tcp_server.rs
This commit fixes a bug where `multi` and chorded keys like `S-b` were not generating key outputs for the purposes of repeat. The new code fixes the issue with hopes to prevent further regressions by changing the keyberon `Action` to be exhaustively matchable and explicitly handling all cases instead of using a catch-all `_ => { ... }` branch.
> fix: add multi key and multi action to key outputs

- docs/config.adoc
- src/main.rs
Notably some hopefully helpful links are added to the long help text and config document. Some rewordings and extra info is added as well.
> doc: change help text and config doc

- src/keys/mod.rs
Hello and thank you for the great work that you do.
First the easy part:  I introduced the "calc" shortcut, which was missing and it was impossible to access this special key of my keyboard.
Now the difficult part that needs discussion: I know that this PR introduces a breaking change, but I didn't know how to handle it.
I handled it how I'd do for my own projects. By properly fixing an old misunderstanding.
From what I see in the sources, there are two completely different keys, the "KEY_EMAIL" and the "KEY_MAIL", with different key codes. In the original code, when defining keys, the "email" key definition had a shortcut "mail", and the "KEY_MAIL" was completely ignored.  With this PR I try to fix this.
Of course as an alternative a new different keycode could be introduced to save the …
> fix KEY_MAIL; support 'calc' keycode

- cfg_samples/kanata.kbd
- docs/config.adoc
- src/cfg/mod.rs
- src/cfg/sexpr.rs
- src/kanata/mod.rs
- src/kanata/windows/interception.rs
This commit implements mouse buttons in defsrc for Windows with the use of the interception driver. It includes a new defcfg item which states which mouse hardware ID to intercept. Since the intended use case is for laptops that have builtin mouse buttons like Lenovo Thinkpads, only a single hardware ID is allowed for now.
This commit also fixes a bug in the parsing which probably only affected the `cmd` action. The bug is that quoted strings keep their quotes when parsed as an atom by the S-expression parser. This was introduced in v1.0.8. This behaviour is not changed; instead, the quotes are trimmed when parsing `cmd` and `defcfg`. If one day the parser is properly fixed to remove the leading and trailing quotes from atoms, then the trimming code should still be fine; `trim_matches` …
> feat(win-interception): implement mouse btns in defsrc

- cfg_samples/kanata.kbd
- docs/config.adoc
- docs/locales.adoc
- src/cfg/mod.rs
- src/keys/mod.rs
This commit adds a new configuration item `defcustomkeys`. This allows a user to define custom keys that can be used without aliases in `defsrc`, `deflayer` and other config items.
The documentation is updated to hopefully encourage community-created resources for non-US keyboard `defsrc` configurations.
Related to #204
> feat: add custom key labels in cfg

- cfg_samples/kanata.kbd
- docs/config.adoc
- src/kanata/mod.rs
This commit adds a configuration to customize the input mode for sequences via a defcfg item: `sequence-input-mode`. One can choose between:
- visible-backspaced
- hidden-suppressed
- hidden-delay-type
The behaviours of these three options are documented in kanata.kbd and config.adoc appropriately. The default option is hidden-suppressed, which matches the old, non-configurable behaviour for sequence input, so as to not break someone who may be depending on or is used to this behaviour.
> feat(sequence): add input mode configuration

- Cargo.lock
- Cargo.toml
- docs/config.adoc
- keyberon/Cargo.toml
- keyberon/src/action.rs
- keyberon/src/layout.rs
This commit changes the keyberon action assertion. The intent of the old assertion was as a bug check in the code and configuration. If a waiting state exists, e.g. tap-dance or tap-hold, then the code should not be performing any actions until that state is done processing. However, the `Custom` action type is special because it has minimal impact on the rest of the keyberon state, and so is fine to allow in. This enables a previously crashing use case, which is fine to not crash on.
In addition, fake keys will no longer interrupt the tap-dance-eager state. This is so fake key actions like on-release-fakekey can be used while in the middle of a tap-dance-eager sequence, which is a requested use case.
> fix(tap-hold-eager): change assert and interruption

- Cargo.lock
- cfg_samples/artsey.kbd
- cfg_samples/kanata.kbd
- docs/config.adoc
- keyberon/Cargo.toml
- keyberon/src/action.rs
- keyberon/src/layout.rs
- src/cfg/mod.rs
- src/kanata/mod.rs
This PR implement input chords as described in https://github.com/jtroo/kanata/issues/99#issuecomment-1331242794.
Staying within keyberon's no-std / config is 'static limitations made some parts of it a bit ugly. In particular I have to leak the entire config twice instead of just once because I first need to parse it before I can resolve which key coordinates participate in a given chords group and I can't just mutate the existing actions because nested actions are usually expressed as `&'static Action` and are therefore immutable, so instead I re-build the actions tree only to leak it a second time.
Same "it's probably fine, how often do you re-load your config" argument as before probably still holds but might be a thing to consider for the future to first parse kanata's config into a …
> feat: add input chords

- Cargo.toml
- cfg_samples/kanata.kbd
- docs/config.adoc
- keyberon/src/action.rs
- keyberon/src/layout.rs
- src/cfg/alloc.rs
- src/cfg/mod.rs
- src/custom_action.rs
- src/kanata/mod.rs
- src/kanata/windows/interception.rs
- src/kanata/windows/mod.rs
- src/layers.rs
- src/tcp_server.rs
This commit fixes the months-old known issue where live reload leaks memory. This is done by tracking "leaked" allocations and freeing them when the layout is dropped.
In the case that a configuration error is found and the layout is not created, the code will clean up those unused allocations as well. The keyberon code is changed to use explicit lifetimes and the Cmd action is changed to use a Vec to catch potential UB.
This makes use of unsafe. The code has been tested in valgrind with no reported memory violations or leaks. The unsafe should be isolated to the `cfg` module.
The `cfg` module makes use of `'static` lifetimes to simplify the code, but restricts users of the generated layout to a shortened lifetime. The Cmd variant of CustomCommand is also changed to use a Vec for safety …
> refactor: free allocated memory on layout drop (v3)

- src/cfg/mod.rs
- test_cfgs/bad_multi.kbd
This commit fixes the configuration parsing to reject multiple waiting actions to be combined in a single `multi`. (tap-dance, tap-hold-*, chord). This is done because such an action will always crash at runtime. The keyberon code cannot handle this type of action and such has an assertion to crash if encountered.
Closes #281
> fix: disallow multiple waiting actions

- .github/workflows/rust.yml
The goal of this commit is to minimize the amount of redownloading and recompiling of kanata's dependencies.
It also runs clippy manually instead of using actions-rs.
> ci: use rust-cache

- Cargo.lock
- Cargo.toml
- src/main.rs
To use this feature, set Type=notify in the systemd service.
An example use case: a tcp client connects to kanata when it receives a notification using dbus which says kanata becomes active. Without this patch, the client will fail to do so because kanata only starts to listen to clients about 2s after it is started.
> feat(linux): notify systemd when kanata has finished starting up

- docs/kmonad_comparison.md
kanata also has a NixOS module. It's even in the nixpkgs[1], which I would say is an advantage over kmonad.
[1]: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/hardware/kanata.nix
> doc: remove an advantage of kmonad

- Cargo.lock
- Cargo.toml
- cfg_samples/kanata.kbd
- docs/config.adoc
- keyberon/Cargo.toml
- keyberon/src/action.rs
- keyberon/src/layout.rs
- src/cfg/mod.rs
This commit adds the `tap-hold-press-timeout` and
`tap-hold-release-timeout` actions, which add a third timeout action that activates instead of tho hold action if the timeout expires as opposed to the hold action being activated by other keys.
Closes #314
> feat: add `-timeout` variants of tap-hold

- src/kanata/mod.rs
Otherwise the lock is held almost continously while any kind of keyberon timer is active. That (at least on Linux) prevents events which bypass kanata (such as mouse movement) from being forwarded in a timly manner (resulting in delayed and low-frequency mouse movement) because the event loop thread will be unable to acquire the lock it needs to output events.
How bad the effect is may depend on OS / kernel version / lock implementation. I've been running the same version of Kanata for a while but the issue has only recently (potentially related to OS updates) been noticeable for me (I put it up to other things in the beginning, so I don't remember exactly when it started happening), though now it is **very** noticeable.
> fix: release lock before sleeping

- docs/config.adoc
This is done in case HTML generation is desired in the future. The auto-generated anchor tags between GitHub and AsciiDoctor are not the same, so this is required for anchor reference links to work.
> doc: set explicit anchor tags on headers

- src/kanata/linux.rs
- src/kanata/windows/llhook.rs
- src/oskbd/windows/interception.rs
Move some comments to be next to the appropriate code, delete a comment that no longer made sense. Remove an unnecessary pub variable.
> refactor: comments, pub

- Cargo.lock
- Cargo.toml
- keyberon/Cargo.toml
- keyberon/src/action.rs
- keyberon/src/layout.rs
- src/cfg/mod.rs
- src/kanata/windows/mod.rs
- src/layers.rs
This commit adds an extra layer of indirection on all slices — which means they are regular pointers instead of fat pointers — to be able to reduce the size of KanataAction to 2 pointers instead of 3 pointers.
This has a performance penalty of an additional indirection for dereferencing slice actions. It also makes the code for creating actions even uglier than it already is. However, it has the performance gain of improving cache locality and reducing total memory footprint by 1/3. Overall it is not clear whether this is a win.
> refactor: reduce size of KanataAction

- Cargo.lock
- Cargo.toml
- cfg_samples/simple.kbd
- src/cfg/error.rs
- src/cfg/mod.rs
- src/cfg/sexpr.rs
- src/kanata/cmd.rs
- src/kanata/mod.rs
- src/main.rs
This commit overhauls the error reporting system in the `cfg` module using the miette crate for nice-looking error messages.
> feat: use miette for pretty errors

- src/kanata/mod.rs
- src/kanata/windows/interception.rs
- src/oskbd/windows/interception.rs
This reverts commit 6af336073d393bcbb4d6847939d54308c0c4329c.
Lately on one of my machines I have encountered issues with the interception driver mechanism dying on me even though kanata appears to be operating just fine. Kanata is able to read the keyboard events just fine and logs writes of the expected keys to the output. However, the key output doesn't work and nothing happens in the OS. I would guess it's caused by use of an interception handle in two different threads.
> fix(wintercept): revert use thread_local IC in oskbd

- Cargo.lock
- Cargo.toml
- keyberon/src/layout.rs
This commit implements code to decompose a longer chord that doesn't have an action mapped into sub-chords that can potentially have actions and activate those actions if they exist.
This requires additional storage in keyberon to keep an action buffer since multiple actions, each with its own CustomEvent, may be activated by a chord decomposition all at once. Without the action buffer, all CustomEvents except the last would be consumed and certain kanata actions wouldn't activate as part of a chord decomposition (actions in the CustomAction enum).
> feat: improve handling of long unmapped chord

- cfg_samples/kanata.kbd
- cfg_samples/minimal.kbd
- docs/config.adoc
- keyberon/src/action.rs
- keyberon/src/layout.rs
- src/cfg/custom_tap_hold.rs
- src/cfg/mod.rs
This commit adds another tap-hold variant that makes use of keyberon's `HoldTapConfig::Custom` variant for the tap hold configuration. The custom variant is used to activate an early tap when any key in the given list is pressed. The goal of this variant is to reduce rolling errors on the same hand when using home-row tap-hold keys.
An unrelated fly-by fix to the minimal.kbd configuration file is added. There was some unintended leftover text that is now deleted.
> feat: tap-hold-release-keys

- src/keys/mod.rs
This PR fixes what I assume to be a typo in three cfg macros, thus making a few previously probably unavailable keys actually available on linux
> Fix typo tagret_os

- Cargo.toml
- README.md
- cfg_samples/minimal.kbd
- cfg_samples/simple.kbd
- docs/release-template.md
Add section on feature flags and shorten by default using collapsible html.
Closes #347
> doc: adjust build/install instructions

- src/keys/windows.rs
> fix(windows): map kprt for use with Interception

- docs/config.adoc
```
[ERROR] Invalid value for windows-altgr: cancel-lctl-release. Valid values are cancel-lctl-press,add-lctl-release
```
> Fix a mistake in docs.

- src/cfg/mod.rs
Fixes #399
Duplicate layer names now cause an error:
```
16:43:18 [ERROR] 
× Error in configuration file
╭─[/home/rszyma/.config/kanata/test.kbd:2:1]
2 │ (deflayer test 1 2 @alias)
3 │ (deflayer test 4 5 6)
·           ──┬─
·             ╰── Error here
4 │ (defalias
╰────
help: duplicate layer name: test
For more info, see the configuration guide or ask in GitHub discussions.
guide : https://github.com/jtroo/kanata/blob/main/docs/config.adoc
ask   : https://github.com/jtroo/kanata/discussions
16:43:18 [ERROR] failed to parse file
```
> fix: bail on duplicate layer name

- Cargo.lock
- Cargo.toml
- src/main.rs
Resolves #394
This uses the `dirs` crate to add `<config_dir>/kanata/kanata.kbd` to the config path
`default_cfg()` checks to see if the file exists before adding it to the path because the check later in `cli_init()` specifically checks the first config file. There is also a new error message for providing no config files provided since an empty vec of config files can be passed through now
> Add config_dir-based file option

- cfg_samples/kanata.kbd
- docs/config.adoc
- src/oskbd/linux.rs
Implemented `REL_WHEEL_HI_RES` and `REL_HWHEEL_HI_RES` for `mwheel-*` actions based on how my mouse sends hi-res scroll events.
From my testing, `(mwheel-down 50 120)` feels the same as before, while `(mwheel-down 5 12)` is much smoother (if an app supports hi res scroll events).
Also I don't know how, but it fixes https://github.com/jtroo/kanata/issues/395
> feat(linux): implement hi res scroll

- cfg_samples/kanata.kbd
- docs/config.adoc
- keyberon/src/action.rs
- keyberon/src/layout.rs
- src/cfg/mod.rs
Implements #389
I haven't tested this. Seems like I could add a unit test to keyberon for this. Will publish for now in case someone wants to do manual testing for me though 😁
> feat: add rpt-any

- src/kanata/mod.rs
- src/main.rs
> feat: add flag to remove delay

- src/kanata/windows/mod.rs
- src/oskbd/linux.rs
- src/oskbd/windows/mod.rs
This commit makes changes to the blast radius of the workaround for issue #138:
> Shift and arrows interact weirdly on a layer
Discovered in this issue was a problem where activating shift on keys other than the physical shift keys, and then also pressing arrow keys, caused stuck-shift behaviour. The fault is, as is typical, Windows' weird behaviour. The workaround added was to release all shift key states if a single shift key state was found to no longer exist, when comparing the previous keyberon state to the current one.
In some cases, this release of shift causes an earlier release of shift than is desired, because some other key activated shift. This commit reduces the blast radius of the shift state releases to only states with the physical lsft key. In hindsight, Windows' weird …
> fix(windows): reduce blast radius of sft-arrow workaround

- cfg_samples/kanata.kbd
- docs/config.adoc
- src/kanata/linux.rs
- src/kanata/mod.rs
- src/oskbd/linux.rs
> feat(linux): add device names options

- src/oskbd/linux.rs
Starting kanata with no devices declared in `linux-dev-names-include` available crashes kanata despite setting `linux-continue-if-no-devs-found` to `yes`. This PR fixes this.
> fix: crash despite `linux-continue-if-no-devs-found` set to `yes`

- src/cfg/error.rs
- src/cfg/mod.rs
- src/cfg/sexpr.rs
- src/cfg/tests.rs
- src/kanata/cmd.rs
Implements #448, obsoletes #456 
Added `file_name` to `Span` as discussed here: https://github.com/jtroo/kanata/pull/456#issuecomment-1599163145
Also added `file_content` to `Span` in similar fashion to `file_name`. I needed to change the way source is provided for `miette`, because errors can now come from different files. Adding another field to `Span` was the easiest way to do this. It shouldn't cause any problems with memory though, because it uses `Rc<str>`.
Removed `cfg_filename` and `cfg_text` from `ParsedState`, since these fields are not really needed anymore.
Some notes regarding the new `include` block:
- Absolute include paths should work.
- Relative include paths have set CWD the same as main config.
- All possible errors I could think of are handled and printed to user.
- If …
> Feat: add `include` block

- docs/config.adoc
mod.rs location changed in #467 but wasn't updated in config.
> doc: update config.adoc link to key name source

- Cargo.lock
- Cargo.toml
- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/Cargo.toml
- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
- parser/src/custom_action.rs
- parser/src/sequences.rs
- src/kanata/mod.rs
Closes #502 
~~Currently untested~~
> feat: on-idle-fakekey action

- docs/config.adoc
- src/kanata/mod.rs
This commit fixes a bug where even if there are multiple ticks of the keyberon state in the processing loop, the idle time ticks would only increment by one.
In addition to the bug fix, some documentation improvements are included.
> fix: accuracy of on-idle ticks + doc changes

- parser/src/cfg/mod.rs
- src/kanata/mod.rs
There are two changes in this commit.
1) Always live reload after ~1s.
After 1 second if live reload is still not done, there might be a key in a stuck state. One known instance where this happens is Win+L to lock the screen when on Windows and using the LLHOOK mechanism. The release of Win and L keys will not be caught by the kanata process when on the lock screen. However, the OS knows that these keys have released - only the kanata state is wrong. And since kanata has a key in a stuck state, without this 1s fallback, live reload would never activate. Having this fallback allows live reload to happen which resets the kanata states.
2) Clear states after ~65.5s of no external input but still not idle.
This code only runs in the LLHOOK Windows version. The reason for this existing is the …
> feat: better handling of Windows LLHOOK stuck keys

- Cargo.lock
- Cargo.toml
- keyberon/Cargo.toml
- parser/Cargo.toml
- src/oskbd/linux.rs
Update Kanata+subcrate versions and update cargo dependencies. Pin serde-derive to version 1.0.171 due to later versions including a binary blob. Pin is-terminal due to later versions causing another transitive dependency to require two incompatible versions.
- Add example to cfg_samples/kanata.kbd
- Added tests, existing tests are sufficient, or did manual testing
> ver: 1.5.0-prerelease-1 + cargo update

- parser/src/cfg/mod.rs
- parser/src/keys/mod.rs
Parse all `deflocalkeys` variants for errors regardless of target OS, but apply only the one based on target OS. 
This PR fixes https://github.com/rszyma/vscode-kanata/issues/1 
- Add example to cfg_samples/kanata.kbd
> parse all deflocalkeys variants regardless of target os

- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
- parser/src/keys/mod.rs
Commit 5dc3296 added code to add the default overridable mappings when clearing the deflocalkeys mappings. This was incorrect because it made it so these default mappings were no longer overridable. In addition to the fix, tests are added to prevent future regressions.
- Add example to cfg_samples/kanata.kbd
> fix: incorrect handling of deflocalkeys default mappings

- cfg_samples/kanata.kbd
- docs/config.adoc
- keyberon/src/layout.rs
- parser/src/cfg/mod.rs
- src/kanata/windows/mod.rs
- src/tests.rs
This commit changes output chord behavior to be more user-friendly by
clearing output chord keys on the next action. I have also been told
(though have not confirmed) that QMK has similar behaviour. I am not
sure that the change in this commit replicates QMK's behaviour
perfectly, but it seems good enough.
Clearing output chord keys on the next action allows a subsequent typed
key to not have modifiers pressed alongside it. Without this change,
typing a new key without first releasing an output chord can have the
unintended typing result. Users have asked about this few times in
issues/discussions and the current workaround is to use a macro.
However, this can be hard to discover. Some users may just be living
with the annoyance because aren't aware that there is a workaround and
they …
> feat!: clear non-oneshot output chord on next action

- parser/src/cfg/list_actions.rs
- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
Before this commit, the error message when a list action was not parenthesized was:
Unknown key/action/variable: {ac:?}
This is not helpful and confusing because the action is valid and exists, but just needs to be in a list. This commit improves the error message to state that the action must be in parentheses.
> feat: improve error message when list action is not in a list

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/mod.rs
- src/kanata/mod.rs
Implement an cfg option to inherit `movemouse` accel state 
https://github.com/jtroo/kanata/discussions/504#discussioncomment-6578201 1st point
https://github.com/jtroo/kanata/issues/549#issuecomment-1696533063 partially
> feat: add movemouse-inherit-accel-state cfg option

- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
Allows passing which deflocalkeys variant to use as argument to parse function.
Merging this PR would allow https://github.com/rszyma/vscode-kanata/pull/4 to move forward.
> parser: allow specifying which deflocalkeys variant to use

- src/kanata/linux.rs
- src/kanata/mod.rs
- src/kanata/windows/interception.rs
- src/kanata/windows/llhook.rs
- src/main.rs
This commit attempts to fix an issue with excessive CPU and memory usage. At the time there are no steps to reproduce, but one suspicion is masses of rogue input events from the kernel. Thus the code is changed to use bounded channels with a reasonably large size (100) that I wouldn't expect to get filled up.
> refactor: use bounded channel

- Cargo.lock
- Cargo.toml
See https://github.com/serde-rs/serde/pull/2590 for more details.
For confirmation that serde_derive no longer ships with blobs, note that the [deblobbing project](https://github.com/commons-rs/serde-deblobbed/commit/92f3ea3b6c5cd8cc201e9ef14f5bb7bfdd1fbf22?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) has been deprecated for this reason.
> dep: Update serde_derive since it no longer ships with binary blobs.

- parser/src/cfg/mod.rs
- parser/src/custom_action.rs
- parser/src/keys/mod.rs
- src/kanata/linux.rs
- src/kanata/mod.rs
- src/kanata/windows/interception.rs
- src/oskbd/linux.rs
- src/oskbd/mod.rs
- src/oskbd/windows/interception.rs
- src/oskbd/windows/mod.rs
Closes https://github.com/jtroo/kanata/issues/553
- For now, implemented only for Linux 
- Allows adding scroll events to `defsrc`
- (Currently) adding any of the new scroll labels to `deflayer` or anywhere else don't error and just outputs nothing. 
- Tested manually, appears functonal.
> feat: add mouse wheel events to defsrc

- docs/config.adoc
This is intentionally omitted from kanata.kbd right now since it is unsupported in the default LLHOOK mechanism of Windows.
> doc: mouse wheel in defsrc

- cfg_samples/kanata.kbd
- docs/config.adoc
- keyberon/src/action/switch.rs
- keyberon/src/layout.rs
- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
Add capability in `switch` to query historically pressed keys. Implements #554.
> feat: add key-history to switch

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/mod.rs
- src/kanata/mod.rs
Add a configurable limit to dynamic macro recording length. The default is 128 keys. This commit closes #595.
> feat!: add configurable limit to dynamic macro

- keyberon/src/action/switch.rs
> fix: add short-circuiting to key-history

- docs/config.adoc
> Fix a typo in config.adoc

- src/kanata/cmd.rs
- src/oskbd/linux.rs
I feel like current logging for cmd action is not enough. This PR fixes it.
> feat: more verbose logging for cmd

- parser/src/keys/linux.rs
- parser/src/keys/mod.rs
- parser/src/keys/windows.rs
- src/kanata/mod.rs
Add a global variable `OSCODE_MAPPING_VARIANT` that can be manually set to use other `OsCode` mapping variant. 
This change will allow me to fix https://github.com/rszyma/vscode-kanata/issues/5.
> parser: allow changing oscode mapping variant at runtime

- docs/config.adoc
- keyberon/src/action/switch.rs
- parser/src/cfg/defcfg.rs
- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
- parser/src/keys/linux.rs
- src/kanata/linux.rs
- src/kanata/mod.rs
- src/kanata/windows/interception.rs
- src/kanata/windows/mod.rs
- src/oskbd/linux.rs
1. Move validation of cfg values to `parse_defcfg` instead of validating them all over the codebase. Reason: before kanata didn't show location when parsing of a cfg value failed, now it does.
2. Replace `HashMap<String, String>` with `CfgOptions`, which holds only validated cfg values. Reason: Allows to easily parse lists as values, since now the actual value parsing is no longer delayed after parser function exited. This was done with #121 in mind.
3. Move cfg options defaults to a `CfgOptions::default`. Reason: it's good to have similar code in one place.
> refactor: validate defcfg values in parser

- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
Improve error messages:
- when parentheses are directly put in `deflayer` (#459)
- when an attempt is made to escape parentheses with `\` in `deflayer` (#163).
Worth noting, that these improved error messages will work only in deflayer, and not in actions.
- Added tests and did manual testing
> feat: improve error messages for when user tries to put parentheses in deflayer directly or escaped with `\`

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/list_actions.rs
- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
- parser/src/custom_action.rs
- src/kanata/mod.rs
Implement unshift and make unmod+unshift key repeat work. Implements #615.
> feat+fix: unshift, key repeat on unmod+unshift

- keyberon/src/layout.rs
- keyberon/src/lib.rs
- keyberon/src/multikey_buffer.rs
Implements #596. This commit adds unsafe code to deal with lifetime/reference shenanigans in keyberon.
Did some manual testing with this config:
```
(defsrc 2 3 4 5)
(deflayer base
(one-shot 1000 lsft)
a
C-b
rpt-any
)
```
> feat!(rpt-any): repeat one-shotted chord

- src/oskbd/linux.rs
Closes #548
Closes #659
Change virtual output device's bus_type from BUS_USB to BUS_I8042.
This fixes the dwt issues for me on Hyprland and I haven't noticed any regression caused by this change.
> fix(linux): libinput "disable while typing" while kanata is running

- Cargo.toml
- README.md
Bump driverkit to v0.1.2 and update the readme. 
closes #676 
- [ N/A] Yes or N/A
- [N/A ] Yes or N/A
- [N/A ] Yes or N/A
- [ N/A] Yes
> Add kext support for macOS version 10

- Cargo.lock
- Cargo.toml
- src/kanata/mod.rs
- src/main.rs
- src/tcp_server.rs
The motivation for this commit is to enable savings on binary size if desired.
This commit turns the TCP server code into an optional feature. The feature is enabled by default for backwards compatibility. Turning off default features saves 81920 bytes from the stripped binary when compiling with release profile when testing on my system.
> feat!: conditionally compile tcp server code

- src/oskbd/linux.rs
This commit adds code to exit on SIGTSTP to avoid hanging onto keyboards while paused. Without this code, pausing kanata can prevent the user from doing anything until they forcefully reboot their system.
- Added tests, or did manual testing: manual testing
> fix(linux): exit on SIGTSTP

- README.md
Change the link of kmonad to point to the original repo instead of its fork.
> Fixed kmonad link pointing to a fork instead of original.

- parser/src/cfg/defcfg.rs
- parser/src/keys/mod.rs
- src/kanata/dynamic_macro.rs
- src/kanata/mod.rs
- src/kanata/windows/mod.rs
Implements #658.
This is a breaking change in behaviour of dynamic macros. I'm not sure that the anyone would really want the old behaviour though. It seems odd that someone might be dependent on it.
Kanata defaults to the new behaviour but can be reverted if desired. I may choose to remove the `defcfg` option though, and **only** have the new behaviour. For now the option is left undocumented, so that I can argue that it is not a breaking change if I choose to remove the option in the future, since the option was never documented ;)
> feat!(dynamic-macro): record and simulate delays by default

- parser/src/cfg/mod.rs
- src/kanata/mod.rs
- src/main.rs
Closes #689
Add `--check` argument. Name not final, but I think it's good enough. No short arg, because `c` is already occupied by cfg file arg, but maybe some other letter could be used.
Additionally fixed bug with `list` argument showing up despite of binary not being compiled for macOS.
Also I've included some other subjective changes regarding logs (see 3rd and 4th commits). I can revert if you don't like them
> feat: add `check` argument

- parser/src/cfg/sexpr.rs
- add `span()` to `SExprMetaData`
- add `pub` to some methods
- remove `PartialOrd` and `Ord` for types, where comparison doesn't make sense 
- move unterminated block comment error catching from `parse` to `parse_`
I need this merged, especially the last thing from the bullet list above to get https://github.com/rszyma/vscode-kanata/pull/13 working correctly.
> parser: small adjustments

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/list_actions.rs
- parser/src/cfg/mod.rs
- parser/src/custom_action.rs
- src/kanata/mod.rs
Implements a new live reload mechanism, which specifies a config file by position. ~~Maybe enables #674.~~ probably not
> feat: implement lrld-num

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/mod.rs
- parser/src/cfg/sexpr.rs
- parser/src/cfg/tests.rs
Add the `concat` keyword to `defvar`. Potentially a breaking change in case someone used the string `concat` as the first string in a list variable at some point. I find the probability of this to be low, but worth noting anyway.
Implements #712.
> feat!: add concat keyword for defvar

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/defcfg.rs
- parser/src/cfg/mod.rs
Add a new defcfg option to block all unmapped (meaning not in defsrc) keys from doing anything. Implements #688.
> feat: add block-unmapped-keys to defcfg

- src/tcp_server.rs
As specified in comment https://github.com/jtroo/kanata/pull/728/files#diff-c204c9e519dac1f19421bbd6234962c60bdae1ca1e617ca696441fdb03247b43R56, server messages should be separated by newlines, but currently aren't. 
- Did manual testing
> tcp: fix server messages not emitting newline terminator

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/defcfg.rs
- src/kanata/mod.rs
- src/kanata/windows/interception.rs
Add capability in Windows+Interception to specify keyboards to intercept and passthrough others.
> feat: windows-interception-keyboard-hwids

- docs/config.adoc
> doc: fix formatting of rapid-event-delay example

- src/kanata/mod.rs
- src/tcp_server.rs
It seems like it's useful to provide layer info to TCP client, since it's quite properly parsing layer names is not trivial, and may be done wrong if client attempted to do so themselves.  
Inspiration to make this PR: https://github.com/reidprichard/window_tools/issues/1#issue-2145533738
> tcp: add layer names request and response

- src/kanata/mod.rs
- src/oskbd/windows/llhook.rs
The following behaviour is changed:
- clear could previously happen multiple times when looping, now it does not
- time until clear is reset on input key input instead of on key output
- releases are done using a keyberon release event instead of clearing the state, which allows custom release handlers to activate
Hopefully closes #785 
> fix(win-llhook): clear-on-idle logic bugs

- docs/config.adoc
- parser/src/cfg/deftemplate.rs
- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
Breaking change: nested lists are now allowed in templates. Since `concat` is only in pre-release versions so far, this seems reasonable to do.
The concat feature is also added into deftemplate to allow using a variable within a string.
> feat!(concat,template): allow nested list in concat, allow concat in template

- src/tcp_server.rs
- tcp_protocol/src/lib.rs
add `SetMouse` as a TCP server action, with x and y as parameters, as described in #623 
I did manual testing with the following command on Windows:
``` sh
echo '{"SetMouse": { "x": 500, "y": 1000 } }' |  winsocat.exe STDIO TCP:127.0.0.1:8089
```
but when testing it moves the mouse cursor to an incorrect position, not a random position, the same position every time, but obviously not a position with the specified coordinates, (500, 1000), I'd guesstimate the position to be (20, 40)
Edit: when running the above command with `"y": 5000` it moves the cursor to a position that seems to have the same X coord but the Y coord is 5 times as …
> [WIP] feat(tcp): add SetMouse action (#623)

- keyberon/src/action.rs
- keyberon/src/layout.rs
- parser/src/cfg/mod.rs
allow defining more chords in `defchords` then just 32, allow up to 128
potentially closes #792 
> feat: allow more participating labels in `defchords`

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/defcfg.rs
- parser/src/cfg/tests.rs
- src/kanata/mod.rs
- src/kanata/windows/interception.rs
Add a list defcfg item for intercepted mouse device hwids with Windows-Interception. The original, single device defcfg item is kept. When both the list and single items exist in defcfg, the single hwid is included in the list.
Closes #764.
~~Currently zero testing, will do later~~
> feat(wintercept): add mouse hwids list defcfg item

- keyberon/src/layout.rs
Implements #743. This is technically a breaking change in behaviour. Hopefully nobody was depending on the old behaviour for a real use case! The expectation is that this is purely an improvement.
> feat!: allow concurrent waiting actions from chord decomposition

- src/tcp_server.rs
- tcp_protocol/src/lib.rs
add `RequestCurrentLayerName` TCP server request type
potentially may partially resolve #811 
> feat(tcp): add `RequestCurrentLayerName` (#811)

- src/kanata/mod.rs
- tcp_protocol/src/lib.rs
after live reload: print layer and send LayerChange event
This PR may supersede/replace PR #813 if you accept this additional change
this PR feature-branch has no conflicts with main as of now, #813's feature-branch does
may partially resolve #811:
> *currently when a file is reloaded and the layer is changed, TCP server does not send a LayerChange event, maybe it should, but I think we still should have this event type
> after lrld: print layer and send LayerChange event (#811,  #813)

- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
- src/kanata/mod.rs
cherry-picked refactor from #775 + rename
> refactor: use struct with named fields instead of tuple for intermediate cfg

- src/oskbd/simulated.rs
- src/oskbd/windows/llhook.rs
Added a better formatted output for simulated events 
- `new` out:↑RAlt 
- `old` out:InputEvent { code: 165, up: true }
-  N/A
-  N/A
-  N/A
- manual
> better output print for simulated events

- docs/config.adoc
- parser/src/cfg/list_actions.rs
- parser/src/cfg/mod.rs
Allow shorter definition of unicode symbols
- unicode 🙁
- 🔣 😀
- [x ] Yes or N/A
- think that for such a tiny change docs are fine, they have an example
-  N/A
- manual
> feat(sym): add a symbol action for shorter unicode definition

- docs/config.adoc
- parser/src/cfg/mod.rs
Use 🔣✗ to print ✗ without having to add an alias and reference it via `@✗` or with `(🔣 ✗)`
Also clarifies the limitation that composed unicode chars (that still look like 1) are not accepted
- [+] Yes or N/A
- N/A, though docs have an example
- N/A
partically fixes #838
> feat(parse) allow direct use of 1-"char" unicode symbols in layers

- docs/config.adoc
- parser/src/cfg/mod.rs
- Use a slightly more meaningful symbol for transparent config `‗` or `≝`
- Use 1 symbol instead of 2 for noop `✗` or `‿` or `∅`
- N/A
> feat(parser) add alternative symbols for transparent and empty

- Cargo.lock
- Cargo.toml
- parser/src/cfg/list_actions.rs
- parser/src/cfg/mod.rs
- parser/src/custom_action.rs
- src/filesim.rs
- src/kanata/mod.rs
- src/tcp_server.rs
- tcp_protocol/Cargo.toml
- tcp_protocol/src/lib.rs
add an action that sends _any arbitrary_ message to TCP clients
may resolve #854 
~~- ⚠️ adds serde dependency to parser/Cargo.toml~~
https://github.com/jtroo/kanata/blob/066740939207fa39a0844ccab97173e9e11749fd/parser/Cargo.toml#L23-L25
~~- ⚠️ removes `Hash` derive attribute from `CustomAction` ~~
~~   - (i'm not experienced enough in Rust to implement Hash for CustomAction and keep the Hash attribute)~~
https://github.com/jtroo/kanata/blob/066740939207fa39a0844ccab97173e9e11749fd/parser/src/custom_action.rs#L11-L14
~~I hope you do not mind adding serde as a dependency to the parser, since almost every rust projects under the sun depends on serde.~~
- Added tests, or did …
> feat: add action that sends any message to clients (#854)

- cfg_samples/deflayer-custom-map.kbd
- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
- src/tests.rs
Add `deflayer-custom-map` which enables an alternate layer definition syntax which is not dependent on `defsrc`, though a `defsrc` is still required (for now).
Closes #842 
- Added tests, and did manual testing
> feat: add `deflayer-custom-map`

- docs/config.adoc
- parser/src/cfg/mod.rs
add missing english/non-symbol modifier prefixes
some people, including me, prefer using the prefixes that do not have the Unicode symbols, they would argue that the English-letter-initials-only prefixes are more readable and less ambiguous:
- `RC-` means **R**ight  **C**trl
- `RS-` means **R**ight **S**hift
- `RM-` means **R**ight **M**eta
- `RA-` means **R**ight **A**lt (didn't add, already in the code)
they mirror the syntax of `C-`, `S-`, `M-`, `A-`, respectively.
...more readable and less ambiguous than `◆›`, `⌘›`, `❖›`, `⎈›`, `⌃›`, `⇧›`,
which mean right meta, right meta, right meta, right ctrl, right ctrl, right shift, respectively. 
(also having/allowing multiple symbols/prefixes/names for one key is a mistake, IMHO, they make other people's configs less readable)
- Add …
> add missing english/non-symbol modifier prefixes

- src/oskbd/macos.rs
Make key display output to always be a 1-char symbol:  ↕ instead of ↓↑
- N/A
- N/A
- N/A
- n/a
> Use a shorter ↕ symbol for tap ↓↑ display 

- docs/config.adoc
- parser/src/cfg/mod.rs
Treat ⎈1 the same as ‹⎈1 (modifier symbols without a side indicator as left)
- N/A
> feat(parser): treat modifier symbols without a side indicator as left

- docs/config.adoc
Before:
After:
Solution found at https://github.com/asciidoctor/asciidoctor/issues/3528
- [X ] Yes or N/A
- [X ] Yes or N/A
- [X ] Yes or N/A
- [X ] Yes
> Fix config.adoc deflayermap underscore character display

- src/oskbd/windows/llhook.rs
Add comments about meaning of llhook parameters (was helpful when reading hook-related code)
Add more explicit win keyboard hook trace message (↓256 instead of just 256)
> doc: add WinAPI hook parameter info and more detailed trace

- parser/src/keys/mod.rs
Added one symbol ⇳🔒 for ScrollLock
Some physical keyboards use ⤓ for this, but currently this is taken by End, which to me is more intuitive, but could change to match the unintuitive reality and remove home/end ⤒⤓ symbols
> feat(parser): add a symbol for ScrollLock

- parser/src/cfg/mod.rs
- simulated_input/src/sim.rs
- src/kanata/mod.rs
- src/oskbd/simulated.rs
Add `new_from_str` for `Kanata` and `Cfg`. The goal is to move towards being able to run a Kanata state machine on the web, which does not have access to files.
Store simulated output strings in a `Vec` instead of printing to stdout immediately. The goal is to give control to the consuming application for where to output the text, e.g. to a web text box instead of stdout.
> refactor: store sim output in Vec, fn to make Kanata from str

- simulated_input/src/sim.rs
- src/kanata/mod.rs
- src/lib.rs
- src/main.rs
- src/tcp_server.rs
I read that using `127.0.0.1` as opposed to `0.0.0.0` (or any other IP address) prevents TCP connections to the server from outside the machine, using `127.0.0.1` (the loopback interface IP address) limits the connections to connections from the local machine, even if the machine's firewall was misconfigured or for some reason is not working.
> use `127.0.0.1` instead of `0.0.0.0` to prevent TCP connections from outside the machine

- Cargo.lock
- cfg_samples/kanata.kbd
- docs/config.adoc
- keyberon/Cargo.toml
- keyberon/src/chord.rs
- keyberon/src/layout.rs
- keyberon/src/lib.rs
- parser/src/cfg/chord.rs
- parser/src/cfg/defcfg.rs
- parser/src/cfg/fake_key.rs
- parser/src/cfg/mod.rs
- parser/src/cfg/switch.rs
- parser/src/cfg/tests.rs
- simulated_input/src/sim.rs
- src/oskbd/simulated.rs
- src/tests.rs
- src/tests/sim_tests.rs
Chords v2 implements global chords with an option to disable chords on specific layers. In the implementation, inputs first go into a separate queue for chords v2 processing. This is in contrast to the existing chords implementation, which uses the same Layout queue as the rest of the keyberon actions.
An advantage of this system is that this enables using the same chord definition on multiple layers without manually changing/defining the key actions of individual keypresses. To contrast the original implementation, actions for an individual key press must also be defined within the chord group.
A notable addition that is adjacent to the chords implementation is the use of simulated tests which work similarly to the existing keyberon tests, but which I find easier to read and write.
It is …
> feat: chords v2 experimental

- parser/src/cfg/mod.rs
- parser/src/cfg/os_dependent.rs
I'm adding graying-out for inactive configuration items in vscode-kanata https://github.com/rszyma/vscode-kanata/pull/30, and I can't elegantly achieve that by just modifying vscode-kanata's code. Please merge :)
- ~Added tests, or~ did manual testing
> feat: add LSP inactive config item hints

- parser/src/cfg/action_visitor.rs
- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
This commit forbids nested transparent actions on the first layer when `delegate-to-first-layer` is enabled.
This change is done because, with the way the current code works, this configuration causes an infinite recursion leading to stack overflow. The behaviour was introduced in commit 089853a which improves the runtime memory consumption of kanata by having only one keyberon layer for each configured layer, instead of having two variants (base + while-held). One of the changes necessary to remove the two layer variants was to modify the `defsrc_layer` with the content of the first defined layer, and it is this change that causes the infinite recursion. It seems undesirable to revert the improvement to enable this niche, and in my opinion, nonsensical use case. This same use case also …
> fix!(transparent): forbid nested trans

- parser/src/cfg/mod.rs
- src/tests.rs
do not duplicate items in `layer_info: Vec<LayerInfo>`  (at parse time)
fixes #945
> do not duplicate items in `layer_info: Vec<LayerInfo>`

- docs/setup-linux.md
Update linux setup documentation to use systemd shell expansion syntax
Require the user to input their sh executable path, but not their home directory or the kanata exec path
documentation:
https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Command%20lines
Context added by jtroo from comments below:
There were unnecessary configurations missing from the instructions; the formatting for dynamically accessing the home directory and the kanata installation location was not functional with systemd because systemd cannot perform shell expansions like subshell, $(which kanata), or path variables, $HOME/.config/....
Instead, we call sh to achieve this dynamic functionality.
Note that the systemd syntax requires a double dollar sign $$ in order to represent the string …
> Fix setup-linux.md to adhere to systemd shell expansion

- docs/config.adoc
rename nonexistent `expand-template` to `template-expand` in config.adoc
> rename nonexistent `expand-template` to `template-expand` in config.adoc

- Cargo.lock
- Cargo.toml
- EnableUIAccess/EnableUIAccess.ahk
- EnableUIAccess/Lib/Cert.ahk
- EnableUIAccess/Lib/Crypt.ahk
- EnableUIAccess/Lib/SignFile.ahk
- EnableUIAccess/Lib/SystemTime.ahk
- build.rs
- docs/config.adoc
- justfile
- src/kanata.exe.manifest.rc
Add a manifest to the kanata.exe Windows binary so that external tools can overwrite it to make it work in elevated contexts. This manifest doesn't have `uia` enabled on its own as this doesn't work with an unsigned binary
So I've also added AutoHotkey scripts that sign the binary (and enable `uia`). Can also add a "compiled" `EnableUIAccess.exe` file to make it simpler and not require AHK installs if you want
- n/a
- n/a
partially addresses https://github.com/jtroo/kanata/issues/831. Fully addressing that would require adding some Windows installer that could self-sign kanata (or sign with a proper $ certificate) and add it to Program …
> feat(win): embed a manifest to allow using kanata in elevated windows

- docs/locales.adoc
Add german locale documentation for macos.
> add german locale for macos

- cfg_samples/kanata.kbd
- docs/config.adoc
- docs/platform-known-issues.adoc
- parser/src/keys/mod.rs
- src/kanata/mod.rs
- src/tests/sim_tests/mod.rs
- src/tests/sim_tests/seq_sim_tests.rs
Add seq keys that are never output as OS events but can participate in sequences.
The seq keys are mapped to a hopefully low-risk set of already-mapped codes (for Linux at least). The advantage of using already-mapped codes is that they won't change purpose in the future. The disadvantage is of course that there are already known uses of these keys. The known purpose is presumed to be low risk for negatively impacting users in practice, and a workaround is to not map keys from `defsrc`.
Maybe closes #950 
> feat(seq): add special seq keys

- docs/fancy_symbols.md
- parser/src/keys/mod.rs
Allows `<` as alias for `lsgt` (non-US backslash). There is an existing `﹨` alias but it's non-ASCII, doesn't represent the actual symbol (on my keyboard, at least) and the character isn't present even in some "big" fonts.
If I can have a green light on this I will also update the docs accordingly.
> feat: allow `<` as alias for `lsgt`

- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
- parser/src/layers.rs
Couple allocations to the layers that use them for better safety.
> refactor: couple KanataLayers with allocations

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/deftemplate.rs
- parser/src/cfg/tests.rs
Use `t!` as a short form of `template-expand`.
The alternative of allowing the template name in the first atom was considered. However, such an implementation would be more difficult and complex. Allowing a shorter prefix atom is a simple and quick implementation.
If one wanted to do the work in the future to allow even shorter template expansion by adding syntax to remove the prefix atom altogether, the added code should not conflict with that work. For now though, the simpler implementation will be added for easier maintenance and hopefully less risk of introducing bugs.
> feat: allow `t!` in place of `template-expand`

- .github/workflows/rust.yml
- src/tests/sim_tests/chord_sim_tests.rs
- wasm/Cargo.lock
Split up pipeline jobs by operating system.
The macOS pipeline has been inconsistently failing for some reason, with an incomprehensible SIGABRT of all things. The main goal of this PR is a shot-in-the-dark that reducing the stuff that runs in the macOS pipeline will help with the consistency.
It's also a generally good improvement anyway because Linux and macOS don't use a bunch of the feature flags that Windows uses.
Some other miscellaneous test+lock changes made it in too, not worth undoing that.
> ci: adjust how jobs run

- src/kanata/key_repeat.rs
- src/kanata/mod.rs
- src/tests/sim_tests/mod.rs
- src/tests/sim_tests/repeat_sim_tests.rs
This commit fixes key repeat in Linux TTY and Windows when a key on the base layer is transparent or unmapped, but process-unmapped-keys is enabled.
This functionality was broken in commit 089853a which changed how layers worked by removing the duplicated base-version and while-held-version of layers, for the benefit of reduced memory consumption.
> fix(repeat): check event code itself for repeat output

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/mod.rs
- parser/src/cfg/permutations.rs
- parser/src/sequences.rs
- src/kanata/mod.rs
- src/kanata/sequences.rs
- src/tests/sim_tests/seq_sim_tests.rs
Gets a lot of the way to #979, with the caveat that it is really quite inconvenient to configure. Perhaps a parser can help.
For example:
- `defchords` can be used for basic single-chords
- for composite/contextual chords, a `defchords` output action can trigger sequences, which themselves can use `O-(...)` for subsequent chords
Example:
```
(defsrc f1)
(deflayer base lrld)
(defcfg process-unmapped-keys yes
sequence-input-mode visible-backspaced
concurrent-tap-hold true)
(deftemplate seq (vk-name seq-keys action)
(defseq $vk-name $seq-keys)
(defvirtualkeys $vk-name $action))
(defvirtualkeys rls-sft (multi (release-key lsft)(release-key rsft)))
(deftemplate rls-sft () (on-press tap-vkey rls-sft) 5)
(defchordsv2-experimental
(d a y) (macro sldr d (t! rls-sft) a y spc nop0) 200 first-release …
```
> feat(sequences): add `O-(...)` for any-order overlapping keys

- src/tests/sim_tests/mod.rs
- src/tests/sim_tests/seq_sim_tests.rs
Add a trait implemented on string to help transform simulated output into more useful/relevant/easy-to-read/easy-to-manipulate text.
> refactor(test): add code to transform sim output

- Cargo.lock
- parser/Cargo.toml
- parser/src/trie.rs
The `patricia_tree` crate is more maintained than the currently-used `radix_trie` crate and uses less memory because the radix_trie crate has radix 16 while the patricia tree has radix 2. Computation cost comparison unknown.. but reducing memory usage is a good thing!
- https://crates.io/crates/patricia_tree
- https://crates.io/crates/radix_trie
Comparison of memory usage:
```
(defseq woa (O-(a b c d e f g h i j)))
patricia_tree:  200 MB
radix_tree:    1700 MB
```
Since overlapped-key sequences generate a sequence for all permutations of the key combinations, having 10 simultaneous keys generates `10! = 3.6M` sequences. I should probably limit this to some reasonable number like 6...
- Update …
> refactor(sequence): use patricia_tree

- Cargo.lock
- Cargo.toml
- src/main.rs
Closes https://github.com/jtroo/kanata/issues/1009
Shorten logged time format.
`time` crate needs to be added to Cargo.toml excplicitly, otherwise `format_description` gives an error.
Before vs after:
```
2024-05-04T17:07:38.975459272+02:00 [INFO] config file is valid
2024-05-04_17:07:59.88683 [INFO] config file is valid
```
> change logged time format to be more concise

- Cargo.lock
- simulated_input/Cargo.toml
- simulated_input/src/sim.rs
Shorten log to the same format as in https://github.com/jtroo/kanata/pull/1011 but for simulated input
- N/A
- N/A
- N/A
> Change logged time format to be more concise on sim

- build.rs
> fix(win): fix '1.7.0-prerelease' not recognized (no 4th number)

- Cargo.toml
- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/defcfg.rs
- src/kanata/mod.rs
- src/oskbd/linux.rs
- src/oskbd/simulated.rs
add defcfg "linux-use-trackpoint-property" to set the pointingstick property on kanata's virtual device. 
resolves #586
I wanted to get some feedback on this approach before completing the checklist.
This is blocked by the bug in evdev-0.12.1, since this patch depends on a method introduced in that version. see emberian/evdev#129
I was initially hoping to dynamically detect trackpoints in `KbdIn` and then alter the virtual device created by `KbdOut` accordingly. However, the `KbdOut` is created first so the dynamic approach would require rearchitecting a bit. 
Instead I opted for a config option. It should be noted that if you change …
> add defcfg "linux-use-trackpoint-property" to set the pointingstick property on kanata's virtual device

- parser/src/cfg/defcfg.rs
- parser/src/cfg/mod.rs
- parser/src/cfg/platform.rs
- parser/src/cfg/sexpr.rs
- parser/src/cfg/str_ext.rs
- src/tests/sim_tests/unicode_sim_tests.rs
Enables outputting of `"` within the `unicode` action by using a Rust-style `r#"..."#` string. I.e. it can be done via `r#"""#`.
This change to syntax _might_ break someone... but I'm not sure if there's any good reason someone might be using this syntax for a real use case today.
As another note, surely there is some better way to remove quotes from atoms than what has been done historically - and how this PR continues to do. But this seems good enough for now. Perhaps unquoting all atoms everywhere in some early parsing step might be a breaking change too?
- Find and modify other places that `r#"..."#` processing should be done
> feat!: enable double-quote within string

- cfg_samples/kanata.kbd
- docs/config.adoc
- src/kanata/cfg_forced.rs
- src/kanata/mod.rs
- src/main.rs
Closes #1018.
No short form is added in case some future flag wants to use it; this flag doesn't seem important enough to warrant the short `-l` variant.
> feat: add --log-layer-changes flag

- Cargo.lock
- Cargo.toml
- docs/platform-known-issues.adoc
- src/oskbd/macos.rs
Implemented `unicode` support for MacOS using the core-graphics crate.
Closes #963 
- N/A - it is already documented. I did remove the docs note that said that `unicode` is unsupported on MacOS
- N/A - already documented
- Yes - I provided error messages, but I am not particularly happy since I don't know what the actual failure scearios are
- Yes, I performed manual testing. If you can give my a hint how/where I can do automated testing I am happy to try my hand at it
> feat: implement unicode for MacOS

- Cargo.toml
Switch to the better llhook input handling methods (only in the new experimental gui app, so should be fine) used in winio2 to avoid issues like https://github.com/jtroo/kanata/issues/1042
- N/A
- N/A
- N/A
> feat(win-gui): Add more correct winiov2 handling method to the gui app

- src/gui/win.rs
Previous `.context` was hiding the errors during the gui building stage, leading to https://github.com/jtroo/kanata/pull/990#issuecomment-2118880088
This fixes it and now it should bubble up the original error
(anyhow's trait isn't implemented for NWG errors, so not sure you can conveniently chain both)
- N/A
- N/A
> Don't hide error message on GUI creation

- src/main.rs
Gui app should have no console when launched with a double-click, but the attribute doing that didn't make it to your main
- N/A
- N/A
- N/A
> fix: add a missing console disabling attribute

- cfg_samples/chords.tsv
- cfg_samples/kanata.kbd
- parser/src/cfg/chord.rs
- parser/src/cfg/mod.rs
This PR is a first shot at implementing a more scalable chording approach using a simple text file for configuration (see https://github.com/jtroo/kanata/issues/979)
https://github.com/jtroo/kanata/assets/35170/d51a4669-ce8c-4355-9124-53c47a1cdd47
> feat: Read chords from simple text file

- docs/config.adoc
- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
enable using vars as layer name 
potentially may partially fix #1027 
- ~error handling in layer_idx() (parser/src/cfg/mod.rs:1669) is bad and needs fixing/improving~
> enable using vars as layer name

- src/gui/win.rs
Allow renaming of `kanata.exe` gui app
Fixes one of https://github.com/jtroo/kanata/pull/990#issuecomment-2119047041
- N/A
- N/A
- N/A
> fix(win,gui): allow renaming of the executable

- justfile
- src/gui/mod.rs
- src/gui/win.rs
- src/kanata/mod.rs
- src/kanata/windows/interception.rs
- src/main_lib/win_gui.rs
Add Interception builds of the Windows GUI app
(also based on the notification PR https://github.com/jtroo/kanata/pull/1031 to make it easier to add later and also test since I can just observe mouse tooltips changing to see whether it works, so will rebase on whatever that one ends up being after review)
By the way, the docs say that
> I think it has something to do with being installed in the privileged location of `system32\drivers`.
But on my system the install script didn't copy/move any of the dlls anywhere, so I guess that's the real reason why it's incosistent - if you copy the dlls to a PATH'ed location, it works, otherwise it fails
Are you sure that you have `interception.dll` in `Windows\system32\drivers`?
Fixes the other part of …
> Add Interception builds of the Windows GUI app

- src/gui/win.rs
- Respect the silence if configured on gui reload via tray
- Fix `icon-match-layer-name` not matching by layer name
Fixes some of https://github.com/jtroo/kanata/pull/1053#issuecomment-2132207192
- N/A
- N/A
- N/A
> fix(gui,win): fix silence and layer icon checks

- parser/src/cfg/mod.rs
Separate mentions of cmd in an executable and user configuration
(what a coincidence, also recently got confused by this message like in https://github.com/jtroo/kanata/discussions/1061)
- N/A
- N/A
> log: update cmd erorr message

- Cargo.lock
- Cargo.toml
- src/main_lib/win_gui.rs
On arg parsing errors at launch when there is no console to show errors to the user, create a `kanata_log.txt`¹ file to record all logging info and then open it with the OS default `.txt` handler
¹ `txt` to make sure some other system logger doesn't open it instead of a text editor, had some issues with this in the past on a Mac
(the proper future way would be to show a gui window, but then what if that fails ;) so this simple workaround would still be useful)
Also might be extended for personal statistics logging https://github.com/jtroo/kanata/issues/259, though that one would be useful with a better serializable format
(again based on top of other PR to avoid conflicts)
- n/a
- n/a
- Update …
> fix(gui): Open a log file on arg parsing errors

- docs/locales.adoc
Add deflocalkeys-linux and defsrc for Swedish keyboard.
A matching transparent deflayer is included to ease the configuration.
- No. Doc added to sub-document locales.adoc.
- N/A
- N/A
- Yes, manually tested by mapping each deflocal key to another key and see that the output is correct.
> doc(locales.adoc): Add Swedish QWERTY layout

- docs/platform-known-issues.adoc
- src/oskbd/macos.rs
Implemented mouse control support for MacOS.
- N/A - already in
- Updated known issues for platforms
- N/A - already in
- Yes
- Yes
> feat: implements mouse control support for MacOS

- docs/config.adoc
- src/oskbd/mod.rs
Add the numeric key code value after the enum literal name in debug prints of KeyEvent.
Printing the numeric key code together with the pressed key enum value makes it much easier to create custom deflocalkeys.
Example --debug output:
```
21:42:09.5202 [DEBUG] (3) kanata_state_machine::kanata: process recv ev KeyEvent { code: KEY_LEFTCTRL (29), value: Press }
21:42:09.6403 [DEBUG] (3) kanata_state_machine::kanata: process recv ev KeyEvent { code: KEY_I (23), value: Press }
```
- N/A
- Yes, short info.
- N/A
- Yes, tested on Linux
It might be a better fit to modify the Debug implementation of OsCode, but I'm not sure how to do it …
> feat: Include numeric key code in KeyEvent Debug

- Cargo.lock
- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/Cargo.toml
- parser/src/cfg/key_outputs.rs
- parser/src/cfg/mod.rs
- parser/src/custom_action.rs
- src/kanata/mod.rs
- src/kanata/windows/mod.rs
- src/tests.rs
- src/tests/sim_tests/mod.rs
- src/tests/sim_tests/override_tests.rs
- src/tests/sim_tests/unmod_sim_tests.rs
Add backwards-compatible change to accept an optional list as the first parameter of `unmod` to specify a specific set of modifiers to temporarily release.
This also includes:
- fix for a test consistency issue on Windows related to the state kept for the numlock shift workaround
- removal of the numlock shift workaround for scancode output because it does not need the code, and the workaround is strictly a downgrade in functionality
> feat(unmod): accept optional mod list as first param

- Cargo.toml
- justfile
This commit adds win_sendinput_send_scancodes as a default feature. The feature has had some time to be tested and should be good enough to replace vkey output by default. With this change, anyone compiling the default kanata binary on Windows without knowing about the difference between vkey codes and scan codes and no awareness of winiov2 will hopefully have a better experience than they used to.
The justfile line for compiling the legacy binary is adjusted as well so that it compiles without the now-default feature and continues to use vkey output, in case someone really needs it.
> refactor(win): adjust default feature flags

- keyberon/src/chord.rs
- keyberon/src/layout.rs
- parser/src/cfg/mod.rs
- src/tests/sim_tests/chord_sim_tests.rs
> fix(chordsv2): interrupt eager hold

- cfg_samples/kanata.kbd
- docs/config.adoc
- keyberon/src/layout.rs
- parser/src/cfg/defcfg.rs
- parser/src/cfg/key_override.rs
- parser/src/cfg/tests.rs
- parser/src/keys/mod.rs
- src/kanata/mod.rs
- src/kanata/sequences.rs
- src/tests/sim_tests/override_tests.rs
> feat(override): add defcfg option to release output early

- docs/config.adoc
should be `all-released` instead of `last-release` which doesn't exist
fixed typo
> typo: correct "Release behaviour" in the configuration guide

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/list_actions.rs
- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
- parser/src/custom_action.rs
- src/kanata/cmd.rs
- src/kanata/mod.rs
This pull request adds a new verb called `cmd-log`. It works exactly like `cmd`, but takes two extra arguments: `<log_level>` and `<error_log_level>`. `<log_level>` is where command to be run, command completion, stdout, and stderr are logged. `<error_log_level>` is where issues running the command are logged. There are five valid levels: `debug`, `info`, `warn`, `error`, and `none`. 
This does not change the behavior or syntax of the normal `cmd`.
Example:
```
cmd-log info error bash -c "echo normal levels"
cmd-log none none bash -c "echo noisy command"
```
Closes #1152 
> feat(cmd-log): add cmd variant for controlling log levels

- docs/locales.adoc
Add Localkey definitions for Swedish QWERTY keyboards on Windows (without intercept nor IOv2)
> Update locales.adoc with Swedish QWERTY for Windows

- src/kanata/mod.rs
Commit 7e5039 broke the force-exit-chord on Windows non-GUI. Seems there is another bug for Windows GUI+Interception; that bug is not fixed in this PR.
> fix(exit): change broken conditional compile logic from gui changes

- README.md
The link to interception is dead, so I figured out the most recent web archive link.
> docs(readme): use archive link for interception

- docs/fancy_symbols.md
Update some outdated key names in the list of fancy symbols. For example, the table says `page_down`, but this throws an error in kanata because it actually expects `pgdn`.
It took me time to find the actual name (I had to use the symbol ⇟ while I found it was `pgdn`), so I think it's beter to put the actual key name in the table. I pressume that `page_down` was used in eralier versions of kanata, which would explain the mismatch. I updated the ones I noticed. Not all of them are fixed I think.
- N/A
- N/A
- N/A
- Yes, I tested the new names: `pgup`, `pgdn`, `spc`, `bspc`, etc.
> Update fancy_symbols.md (fix many outdated symbols)

- src/kanata/mod.rs
The unmod example at https://github.com/jtroo/kanata/blob/main/docs/config.adoc#unmod doesn't work, this fixes it.
> fix unmod (lalt)

- docs/config.adoc
It has taken me a while to figure out why `unmod` had no effect in my mappings. After running in debug mode I realized that the events sent by the modifiers are not tracked at all, since they are not part of my source mapping. When seeing this I remembered seeing `process-unmapped-keys` enabled in [this comment](https://github.com/jtroo/kanata/issues/615#issuecomment-1803448264) while digging through some issues. Doing so resulted in the expected behavior.
> doc: add note about `process-unmapped-keys` to `unmod`

- parser/src/cfg/mod.rs
- parser/src/cfg/sexpr.rs
may fix https://github.com/jtroo/kanata/issues/1236, it fixes the behavior according to my manual testing, but not sure if the fix is a "correct" fix (in the sense of a "correct program").
Edit: may fix #1220 too apparently.
- Added tests
-  [ ] Yes
- did manual testing
> fix "any key" mappings in `deflayermap`

- justfile
fixes https://github.com/jtroo/kanata/issues/1190
Remove extra space between comma-seperated arguments in the just build file
- N/A
- N/A
- N/A
> fix(wintercept): remove extra whitespace in the build script cli args

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/defcfg.rs
- parser/src/cfg/tests.rs
- src/kanata/mod.rs
- src/oskbd/linux.rs
- src/oskbd/simulated.rs
> feat(linux): allow configuring output device bus type

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
- parser/src/custom_action.rs
- src/kanata/mod.rs
- src/tests/sim_tests/mod.rs
- src/tests/sim_tests/release_sim_tests.rs
> feat: add `reverse-release-order` action

- keyberon/src/layout.rs
- src/tests/sim_tests/chord_sim_tests.rs
Fixes #1199, kinda. Macro no longer consumes other macro outputs but doesn't fix the exact described use case.
> fix(macro): keep macro states on macro completion

- src/oskbd/sim_passthru.rs
Just fix up a method signature.
- [ ✅] Yes or N/A
- [ ✅] Yes or N/A
- [ ✅] Yes or N/A
- [ ✅] Yes
> Fix compile error on Linux with simulated_input

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/defcfg.rs
- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
- parser/src/cfg/tests/device_detect.rs
- parser/src/keys/mod.rs
- src/kanata/linux.rs
- src/kanata/mod.rs
- src/oskbd/linux.rs
> feat(linux): add `linux-device-detect-mode` to defcfg

- docs/config.adoc
- parser/src/cfg/mod.rs
- parser/src/cfg/tests.rs
- parser/test_cfgs/include-good-optional-absent.kbd
Up to now files to be included need to exist. With these changes any non-existing file is just ignored.
> feat: allow for include files to be absent

- Cargo.lock
- Cargo.toml
- src/oskbd/macos.rs
This PR adds drag-and-drop capabilities for Mac OS.
The code was taken from [RustDesk](https://github.com/rustdesk/rustdesk/blob/4f7e10bac6d09f9364edcd2983ce36b0a2e90cb9/libs/enigo/src/macos/macos_impl.rs#L191-L210).
> Implement mouse drag for Mac OS

- src/oskbd/windows/mod.rs
This fixes an issue where keypad enter was not working correctly. I'm not entirely sure why the conditional compile branch was written in the first place; maybe I defaulted to it without thinking much about it. But it seems correct to use osc_to_u16 regardless of llhook reading mechanism given that output VK doesn't care about input reading mode.
> fix(windows): use osc_to_u16 even without read scancode

- keyberon/src/layout.rs
- parser/src/keys/mod.rs
- src/kanata/mod.rs
- src/kanata/windows/llhook.rs
- src/oskbd/windows/exthook_os.rs
- src/oskbd/windows/llhook.rs
Synchronize Kanata and Windows keystates.
> fix(win-llhook): before blocking, check bad keystates

- cfg_samples/kanata.kbd
- docs/config.adoc
- keyberon/src/action.rs
- keyberon/src/layout.rs
- parser/src/cfg/key_outputs.rs
- parser/src/cfg/mod.rs
- src/kanata/output_logic/zippychord.rs
- src/tests/sim_tests/mod.rs
- src/tests/sim_tests/use_defsrc_sim_tests.rs
Related to #1255
Potentially a breaking change in case someone has decided to use the string `use-defsrc` within a `deflocalkeys` variant. I considered a shorter name like `src` but that seemed like a higher risk of actually being used within `deflocalkeys` due to its brevity. Thus the verbose name `use-defsrc`.
> feat: add `use-defsrc` action

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/fake_key.rs
- parser/src/cfg/list_actions.rs
- parser/src/cfg/mod.rs
- parser/src/custom_action.rs
- src/kanata/mod.rs
- src/tests/sim_tests/mod.rs
- src/tests/sim_tests/vkey_sim_tests.rs
Implements https://github.com/jtroo/kanata/issues/1306
> feat(vkeys): add hold-for-duration action

- src/kanata/output_logic/zippychord.rs
- src/oskbd/linux.rs
Autodetection is based on checking a single key capability, `KEY_ENTER`. For some reason, some input devices are split into multiple devices, and likely only one of them has `KEY_ENTER` while the others do not. Today the `include` option will still ignore devices that are autodetected to not be keyboards. This commit fixes the use case where a device that is **not** being autodetected but is desired to be grabbed by Kanata is being referenced by its device name rather than path.
> fix!(linux): include name should disregard autodetect classification

- src/kanata/output_logic/zippychord.rs
- src/tests/sim_tests/zippychord_sim_tests.rs
I noticed that after zippy-chording the `RAlt` Key got stuck until I used another `RAlt` key.
This PR releases `RAlt` the same way it is done for the Shift keys.
I added a test by copy & pasting from the Shift tests and modifying it such that it works with the fixed implementation and fails with the old one.
> fix: Release RAlt after zippy-chording

- src/oskbd/linux.rs
Regarding https://github.com/jtroo/kanata/issues/1268.
> Identify more devices as keyboards

- docs/config.adoc
Corrrect the typo "dactivate" to "deactivate" in config.adoc
> Corrrect the typo "dactivate" to "deactivate" in config.adoc

- docs/config.adoc
Change typo 'An list' to 'A list'
> Correct typo in config.adoc

- docs/config.adoc
Change `tap-hold-*` actions from variables in the table to actions. 
Also, change behaviour (British) to behavior (American) to remove the various spell checks' red underlines including Grammarly. Perhaps not that important.
> Correct typos for `tap-hold-*` in config.adoc

- docs/setup-linux.md
This change recommends using a higher
(in fact, the highest) CPU and IO priority
to the kanata process.
While this is not such an obvious default
due to the mouse being by default captured by kanata, the change still makes sense as keyboard input
is likely seen as a real-time priority for kanata users.
Additionally, I've removed the DISPLAY environment variable from the service. It's not needed.
Kanata works entirely outside of Xorg.
Nor does it have a GUI that would need to be shown.
- [N/A] Yes or N/A
- [N/A] Yes or N/A
- [N/A] Yes or N/A
- [Yes] Yes  (I did a manual testing. It's what I'm using locally.)
> Recommend high priority for Linux

- parser/src/cfg/fake_key.rs
- parser/src/cfg/mod.rs
- parser/src/cfg/switch.rs
use `parse_vkey_coord` when parsing vkeys in switch because it internally calls `set_virtual_key_reference_lsp_hint` which we want to be called in order to add lsp hints for vkeys in switch.
> fix: add lsp hints for vkeys in switch

- docs/config.adoc
Fix the second example config in the "Sequences" section of config.adoc. [kanata simulator link showing the original error](https://jtroo.github.io?data=BQEwpgZgzgTgxgAggdgWiAONSCc2ICMADAJQBQokANgIYCeYMCARjVGGdlwlFSEwDsA9gAciCYSIITRAJnKUIAFzABbEbRU8wARwTAAbgGsAtAJqqwCAJYCRAVyUmjYOlARDHDpzThLrQgLk3Ni8-IoG1jBK9jRULm4IACTGZhZWSZ5K3ia+-oHBITx8MIrseimm5pbJtjkJUOTkANzNCCrqmmAmYAAeIjQCIAgAFmwINDwjQtFgAmDDEDOqAFztAIQUSuvaeiBCSnBCqvqS4pIEJPqqvjBCCAB0CIj3qiQK27sI+0ozAOanUTnORXYA3OB3R4eBBMP7vAA+iKRyJR8JAKwAYqglCsMOJ7JjsSsACw4cTojFYHGkhAEyntFYAZkZqDIFLwOIAbKg6RyVshkABWb6EhkYRm00U4xlECVszFUkl4OmKxkYPAU4gM5mSjFanFkohEIA). Here is the [fixed version](https://jtroo.github.io?data=BQEwpgZgzgTgxgAggdgWiAONSCc2ICMADAJQBQokANgIYCeYMCARjVGGdlwlFSEwDsA9gAciCYSIITRAJnKUIAFzABbEbRU8wARwTAAbgGsAtAJqqwCAJYCRAVyUmjY …
> doc: fix example 2 in the "Sequences" section of config.adoc

- Cargo.lock
- Cargo.toml
- docs/config.adoc
- parser/src/cfg/defcfg.rs
- src/kanata/macos.rs
- src/kanata/mod.rs
- src/oskbd/macos.rs
Hi,
This PR implements `macos-dev-names-exclude` config by reading output from stdout as karabiner driver does to return the keyboard list. This partially addresses https://github.com/jtroo/kanata/issues/1033.
This currently does have one limitation: if `macos-dev-names-include` is provided then it takes precedence over `macos-dev-names-exclude`. We can use their set difference if so desired.
> feat: `macos-dev-names-exclude`  config added and implemented

- docs/config.adoc
The documentation mentioned
1. that variables are prefixed by @ and
2. that variables are prefixed by $
This commit tries to fix this contradiction and to simplify the wording a bit.
> [DOC] small modification of config.adoc

- src/kanata/linux.rs
- src/oskbd/linux.rs
Fix infinite memory growth when a device has an endless event stream.
> fix(linux): limit event reading

- docs/config.adoc
Clarify use of `linux-dev-names-include` configuration option.
Resolves #1511
> Clarify use of linux-dev-names-include

- docs/config.adoc
Remove extra parentheses around aliases.
> doc: fix alias for clipboard template

- parser/src/keys/macos.rs
- parser/src/keys/mod.rs
Add the missing key codes for the fn row key on mac.
More specifically:
* mission control
* spot light search
* dictation
* launch pad
* do not disturb — unfortunately this one is not yet working
> feat(macOS): add missing macos fn row keys

- parser/src/cfg/list_actions.rs
- parser/src/cfg/mod.rs
- parser/src/custom_action.rs
- src/kanata/mod.rs
- src/kanata/sequences.rs
- src/tests/sim_tests/seq_sim_tests.rs
Implements https://github.com/jtroo/kanata/issues/1477
> feat: add sequence-noerase

- docs/locales.adoc
Added a 100% keyboard defsrc with only event.code in it to locales.adoc.
Works on my Arch Linux installation
> locales.adoc: Adding a 100% keyboard defsrc, event.code only

- src/tcp_server.rs
The step_by call was originally done because there used to be two versions of the same layer; one which was the target of `layer-switch` and the other which was the target of `layer-while-held`. This has since been changed and there is only one version of each layer now, so the step_by needs to be removed now.
> fix(tcp): do not skip layer names

- README.md
Add a reference to OverKeys in the `README.md` file to provide information about its integration and usage.
> doc: add reference to OverKeys in README.md

- src/oskbd/macos.rs
- src/tests/sim_tests/unicode_sim_tests.rs
https://github.com/jtroo/kanata/issues/1546
Avoid sending trailing NUL byte in Unicode events
Previously, a fixed two-element array was used regardless of the actual
number of UTF-16 code units, causing an extra NUL byte to be passed to VSCode
when inserting Unicode characters. This change uses the slice returned by
`encode_utf16` to ensure only the valid code units are sent.
I have zero experience on rust but it fixed the issue
- [] Yes or N/A
> fix: unicode on macos print nul byte

- cfg_samples/kanata.kbd
- docs/config.adoc
- parser/src/cfg/defcfg.rs
- parser/src/cfg/tests.rs
- src/kanata/mod.rs
- src/oskbd/linux.rs
- src/oskbd/sim_passthru.rs
- src/oskbd/simulated.rs
Provide a configuration option to set the name of the virtual device on linux.
> feat(linux): add virtual device output name configuration

- .github/workflows/windows-build.yml
Closes #1599
- [N/A ] Yes or N/A
- [ N/A] Yes or N/A
- [N/A ] Yes or N/A
- [Yes] Yes
> ci: Add windows x64 build action

- cfg_samples/kanata.kbd
- docs/config.adoc
- docs/simulated_output/sim.kbd
- docs/simulated_passthru_ahk/kanata_dll.kbd
- keyberon/src/layout.rs
- parser/src/cfg/mod.rs
Closes #1428
- [N/A] Yes or N/A
- [ N/A] Yes or N/A
- [ N/A] Yes or N/A
- [ N/A] Yes
> refactor: Renames references for tap-timeout to tap-repress-timeout

- keyberon/src/layout.rs
- src/tests/sim_tests/chord_sim_tests.rs
- src/tests/sim_tests/mod.rs
- src/tests/sim_tests/tap_hold_tests.rs
> fix: delayed tap-hold release can now tap

- src/tests/sim_tests/mod.rs
One can activate a specific set of features so that the zippychord_sim_tests test is run without the zippychord feature being enabled. This leads to a runtime error saying that the zippychord feature was not enabled when trying to run the tests with this specific feature set.
Add an additional cfg feature gate in front of the zippychord_sim_tests module to prevent this failure.
> Only test zippychord when feature is enabled

- Cargo.lock
- Cargo.toml
- src/kanata/millisecond_counting.rs
- src/kanata/mod.rs
- src/tests/sim_tests/timing_tests.rs
The instant crate is no longer maintained since a year. Its upstream author recommends [1] to switch to the web-time crate [2], which this commit does.
[1] https://github.com/sebcrozet/instant/commit/d94bebae9fa470869dda4c1c916ac3686c7bc9bd
[2] https://crates.io/crates/web-time
> refactor: replace instant dep with web-time

- keyberon/src/layout.rs
- src/kanata/sequences.rs
- src/tests/sim_tests/seq_sim_tests.rs
Potentially breaking fix as this changes output order. However, I suspect this will not break anyone and would be a strict improvement, so I opt not to make it configurable. If someone reports a break, can add the configurability later.
Closes #1701 
> fix!(sequences): prioritize vkey tap of seq completion

- docs/config.adoc
acceletaion ->  accele*rat*ion
Fix tiny typo in config.adoc.
acceletaion ->  accele**rat**ion
- [N/A]
- [N/A
- [N/A]
- [N/A]
> fix tiny typo in config.adoc

- parser/src/keys/macos.rs
This patch fixes the `todo` for KeyboardApplication, which is actually the `menu`/`compose` key.
This prevents a panic when emitting the `menu` key on macOS.
- N/A
- N/A
- N/A
> fix(macOS): emit the correct OsCode for `compose`

- src/tcp_server.rs
The TCP server crashes whenever `peer_addr()` fails on incoming connections. This happens when clients disconnect suddenly or during TCP resets, causing the whole app to panic with `.expect()`. Not great for stability!
Instead of panicking, we now handle the error gracefully:
- Catch `peer_addr()` failures with a proper match statement
- Fall back to a unique identifier using the stream's memory address
- Log a warning so you can still see what happened
- **src/tcp_server.rs**: Swapped out the panic-happy `.expect("incoming conn has known address")` with error handling that creates a fallback ID like `unknown_12345678`
I originally contributed the TCP server code and ran into this crash while testing locally when network conditions got rough.
- ✅ All tests still pass 
- ✅ Clippy is happy …
> fix(tcp): Handle peer_addr() failures gracefully to prevent panics

- docs/setup-linux.md
- src/kanata/mod.rs
Fix #1798 and fix #1799.
Before merging need confirmation if this works fine for systemd before v258; otherwise would need to add other instructions for users to change command based on system info.
> doc: update linux instructions
